### ISSUE TITLE
should loris.conf be renamed loris2.conf?

### ISSUE THREAD

**Issue by jpstroop** [loris-imageserver/loris#105]
May help with running mutiple versions

**Comment by regisrob** [comment]
+1. It would prevent to modify setup.py and webapp.py each time you want to deploy a new version

**Comment by jpstroop** [comment]
Thanks, that's exactly what I was thinking. I assume you're running
multiple versions on one server--was there anything else you had to do to
make that possible?

(ping @azaroth42)

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by regisrob** [comment]
Yes I have two instances on the same server, and I only had to follow these steps to make them coexist:
- change ETC_DP to '/etc/loris2' in setup.py and webapp.py 
- get round the default behavior with KDU binary and shared library coming with Loris 2 (avoid the files already existing on the system to be overwritten at setup by those provided by Loris)

That's all, I think.

**Comment by jpstroop** [comment]
Do with #63 and before #98

**Comment by jpstroop** [comment]
@regisrob You must have two versions of Loris on your PYTHONPATH. How does the WSGI script (/var/www/loris/loris.wsgi) know which to import?

**Comment by regisrob** [comment]
Loris 2 is built in a separate virtualenv and loris.wsgi is located in a separate folder. I have this config on my test server:

**Loris 1:** /var/www/iiif/loris/loris.wsgi
with: site.addsitedir('/usr/local/loris/lib/python2.7/site-packages')

**Loris 2:** /var/www/iiif/loris2/loris.wsgi
with: site.addsitedir('/mnt/vdata/opt/loris2/env/lib/python2.7/site-packages')

... and the Apache part in the respective vhosts config files.

Is there something inconsequent? Is there a better way to deploy multiple instances?

Thx
