### ISSUE TITLE
Support Python 2.6

### ISSUE THREAD

**Issue by jpstroop** [loris-imageserver/loris#110]
For those like @azaroth42 stuck on RedHat/CentOS. :smile:

**Comment by azaroth42** [comment]
RHEL = :crying_cat_face:

**Comment by jpstroop** [comment]
@azaroth42 Good to go.

Changes were:
- Conditionally importing `OrderedDict` from `ordereddict`, as discussed,
- Changing `Decimal` constructors to use strings instead of floats (sometimes resulting in an extra cast, but I don't think it's that big a deal, and I could probably tidy it up a bit more), and
- Using an older syntax for unit testing that exceptions are raised, [e.g. this](https://github.com/pulibrary/loris/commit/725068c0087762dbcc1293886a1410f35833fe76#diff-924b9f09ffec5e523fa8484868c8c85bL110).

I tested with python 2.6.3, 2.6.5, and 2.6.9. < 2.6.3 may work, but I couldn't get them to compile on my system. Travis is testing 2.6(.?) and 2.7 now as well.

**Comment by jpstroop** [comment]
Ping @mmcclimon, in case this interests you.

**Comment by jpstroop** [comment]
(and re: RHEL--eventually it'll be _extra_ secure because nobody will flippin; use it!) :smile_cat:

**Comment by azaroth42** [comment]
Sweet! Thanks @jpstroop :beer: That will indeed make life MUCH easier on ouRHELl.

**Comment by bcail** [comment]
@jpstroop is Loris still supporting python 2.6? Looks like 2.6 isn't in .travis.yml anymore...

**Comment by jpstroop** [comment]
Can give it a try, I feel like we might have run into an issue the `requests` library and CentOS (not even RHEL) that 2.6 couldn't support. @azaroth42, do you remember?
