### ISSUE TITLE
Absolute file system path in @id when source image is jpg

### ISSUE THREAD

**Issue by regisrob** [loris-imageserver/loris#112]
While testing Rob's validator, I noticed that info.json returns the absolute file system path when requesting a jpg file as source image (I'm using the latest dev build): 
See http://interne.biblissima-condorcet.fr/loris2/67352ccc-d1b0-11e1-89ae-279075081939.jpg/info.json

**Comment by jpstroop** [comment]
Hmmm..
I can't seem to reproduce this, either with the embedded dev server or behind apache. The fact that it's happening with JPGs only also seems a little weird. It's not happening with your JP2s, correct?

Could you clear the cache of that file, restart, and try again? If that doesn't work, could you turn your logging up to 'DEBUG' and send me the statements from the info request?

**Comment by regisrob** [comment]
Cleaning the cache did the trick! (sorry). Weird, I'm sure I saw an "/mnt/vdata/..." at some point, although I was a bit tired this afternoon :tired_face:

Loris scores 29/31 in the validator :ok_hand:

**Comment by jpstroop** [comment]
Cool...that one had me confused! 

Haven't had a chance to run against the validator, but I'll have it to 31/31 (or better) by the end of the week!

**Comment by regisrob** [comment]
Woo hoo!
![loris-3](https://cloud.githubusercontent.com/assets/402117/3958224/f33bd67a-271d-11e4-861f-1646ace08da3.jpg)

**Comment by jpstroop** [comment]
Man, that was going to be in my release announcement!

![loris-gif](http://www.pbh2.com/wordpress/wp-content/uploads/2013/06/cutest-slow-loris-gifs-tickle.gif)
