### ISSUE TITLE
Log error message if tmp directory is not readable/writeable

### ISSUE THREAD

**Issue by schwemmer** [loris-imageserver/loris#127]
I've run into this a couple of times while installing and experimenting with Loris: when requesting an image and the tmp directory is not readable or writeable you get an internal server error but the log does not show any error so it is a bit difficult to figure out what the problem is. The solution was to do a

`sudo chown -R loris /tmp/loris/tmp`
`sudo chgrp -R loris /tmp/loris/tmp`

It would be nice if the log would say "Error: /tmp/loris/tmp is not readable/writeable, please update file permissions" or something similar.

**Comment by schwemmer** [comment]
Upon further investigation I could find the error being logged to the apache2 error.log:

`CalledProcessError: Command '/usr/bin/mkfifo /tmp/loris/tmp/jp2/brrgp.bmp' returned non-zero exit status 1`
`/usr/bin/mkfifo: cannot create fifo '/tmp/loris/tmp/jp2/ddfzi.bmp': Permission denied`

It would still be useful if something was logged to the loris log file though. I think the same applies if the source image is not readable because of wrong file permissions.

**Comment by jpstroop** [comment]
I've run into it too...just never bothered doing anything about it :sleepy:. I think this takes care of it.

**Comment by schwemmer** [comment]
Great, thanks!
