### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by jpstroop** [loris-imageserver/loris#133]
- [ ] `pip install -r requirements.txt` before setup.py
- [ ] need `python-dev` from apt
- [ ] incorporate Debian variances from Ubuntu
- [ ] Apache config instructions should point to `loris2.wsgi`

**Comment by rlskoeser** [comment]
Can't all of the python requirements go into setup.py install_requires instead of needing an additional manual step?

Semi-related question: are there any plans to publish loris on pypi so it can be pip installable?  I vaguely recall there might be issues with the kakadu stuff but I can't remember and I'm having trouble finding anything that references that in the current issues.

Another question: the installation documentation doesn't say anything about how you are expected to get loris itself.  Are you assuming that people are checking out from github and/or downloading a zip or tar.gz from the release page?  I think it should be possible to pip install from a github url, so even if you can't put a package on pypi for some reason adding a note about how to use pip for installation still seems like it would be convenient.

**Comment by jpstroop** [comment]
> Can't all of the python requirements go into setup.py install_requires instead of needing an additional manual step?

We're crossing threads :smile: See my response over on #138, but let's continue the conversation here.

> Semi-related question: are there any plans to publish loris on pypi so it can be pip installable? I vaguely recall there might be issues with the kakadu stuff but I can't remember and I'm having trouble finding anything that references that in the current issues.

Yes, kakadu is a problem. It's possible that one could set it up with everything but kakadu, but I'm very concerned about people having a bad experience and walking away without understanding why. And, at least on 64-bit Ubuntu systems you have to do [this nasty stuff](https://github.com/pulibrary/loris/blob/development/.travis.yml#L10-L16) to get Pillow to work at all. Can you create arbitrary symlinks on people's systems using pypi?

> Another question: the installation documentation doesn't say anything about how you are expected to get loris itself. Are you assuming that people are checking out from github and/or downloading a zip or tar.gz from the release page?

That has been my assumption, yes, and possibly a github-hosted website at some point; I just haven't had the time for the latter.

As I said earlier, I'd love for all of this to be easier...it's really just the dependency headaches and a lack of available cycles on my part to work it out. I'd be happy to see someone take a crack at it!

**Comment by rlskoeser** [comment]
> We're crossing threads ...

Whoops, I wasn't paying attention to which issue I was commenting on.  Sorry about that.  I agree, this is a better place to discuss it. 

I'll summarize my comments/suggestions here so we have them in the right place.
- figure out how to remove configobj dep before running setup.py 
- move requirements.txt deps into setup.py install_requires (or at least reduce to reqs file to configobj)
- consider using scripts= for cache cleaning scripts etc vs. data_files for better compatibility with virtualenv

The symlink stuff looks painful.  I'll see if I can get one of our sysadmins to take a look at it.

**Comment by jpstroop** [comment]
Bring stuff over from the other thread (and commenting on it):

> I noticed the configobj dependency; that is a little troubling. Why is it needed before setup can run? Is the config file supposed to exist before loris is even installed?

Because it looks at the config file to figure out where all of the various directories should be and where the kakadu dependencies are. It would quite a lot to pass in as options, but I guess an alternative would be really hard code everything in the setup script and then you to move it later if you stray from the defaults. Do you think that would be better?

> FYI, it occurs to me that hard-coding the script install paths likely means that loris probably wouldn't install very well inside a virtualenv

We're using virtualenv in production here. [Check this out](https://github.com/pulibrary/loris/blob/development/doc/two_lorises.md).

> I tried to look at your setup script before and it seemed pretty complicated. I guess it is doing a lot of work to get everything set up the way it needs to be.

I guess that just comes down to local preferences. Here the preference tends to be to put everything in the conventional *nix locations, eg. /usr/local/bin for scripts, etc.

Could it all be easier if everything went to, e.g., `/usr/local/lib/loris` and then the cache, config, bin, and lib were under that? It doesn't sit well with me, but it's an option I suppose.

**Comment by rlskoeser** [comment]
Glad to know you're using virtualenv.  I'd have to check with our sysadmins on installing to conventional unix locations vs inside the virtualenv; but if you're installing two different versions in a virtualenv, wouldn't the second one overwrite the scripts from the first?

So is the setup script installing to paths in the config file packaged with the source code?  And the idea would be that if you don't want the default paths you would have to edit the conf file inside the checked-out source before running the installation script?  That seems a little circular, and not exactly compatible with an automated install.

This makes me wonder if you're trying to do too much in the setup.py script.  Maybe settings that users are likely to want to configure (e.g., cache directories) shouldn't be handled by the setup script.
