### ISSUE TITLE
Installer is failing

### ISSUE THREAD

**Issue by vruwink** [loris-imageserver/loris#150]
Hi,
Trying to get Loris installed on an Ubuntu 14.04 VM, but I keep running into this error when I run ./setup.py install:

Traceback (most recent call last):
  File "./setup.py", line 65, in <module>
    cache_links = config['img.ImageCache']['cache_links']
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 567, in **getitem**
    val = dict.**getitem**(self, key)
KeyError: 'cache_links'

It's possible I missed a dependency somewhere, but I can't find what it is.  Any insights?
Thanks.

**Comment by jpstroop** [comment]
This isn't you. There isn't test coverage for the setup script, and this was introduced when the caching strategy was changed a few commits back. Watch for a patch within 30 minutes. 

Thanks for catching this. My apologies.

**Comment by vruwink** [comment]
Wow! Thanks for the fast response.   :+1:
