### ISSUE TITLE
2.0.1 release notes

### ISSUE THREAD

**Issue by jpstroop** [loris-imageserver/loris#167]
Better late than never....

@eliotjordan @scande3 @rlskoeser would you mind giving this a read?

https://github.com/loris-imageserver/loris/releases/tag/2.0.1

**Comment by eliotjordan** [comment]
Looks good.

**Comment by scande3** [comment]
@jpstroop - would it be worth noting the change in the resolver namespacing? (ie. "SimpleHTTPResolver" becomes "loris.resolver.SimpleHTTPResolver" in your config if you are simply upgrading).

Looks good to me otherwise. :+1:

**Comment by jpstroop** [comment]
Good idea, thanks. Done.
