### ISSUE TITLE
bug: missing key in PIL_MODES_TO_QUALITIES 

### ISSUE THREAD

**Issue by ehenneken** [loris-imageserver/loris#170]
The dictionary `PIL_MODES_TO_QUALITIES` in `img_info.py` is expected to have a key `LA` for some images. The attached image threw an internal server error because of this. Apparently this is an "L" image with "alpha" (see: http://pillow.readthedocs.org/en/latest/handbook/concepts.html)
![astro-ph_0312526_f2](https://cloud.githubusercontent.com/assets/273358/8483915/3bb16caa-20c2-11e5-97e6-f575dd0b968d.png)

**Comment by jpstroop** [comment]
Thanks for the fixture. I'll look into it now.
