### ISSUE TITLE
Problem with loris-http_cache_clean.sh

### ISSUE THREAD

**Issue by gvasold** [loris-imageserver/loris#175]
Got errors running loris-http_cache_clean.sh. Seems to work now. Here is my small patch:
https://gist.github.com/gvasold/da96513504437cc0762a

**Comment by jpstroop** [comment]
This seems reasonable. I'm not sure how it would have worked before! @scande3 ??

**Comment by scande3** [comment]
@jpstroop - I must have had an older version checked in that I had deployed on our server when I did that pull request. :+1: to merging this though.

(Surprised no one else made an issue about it before now).

**Comment by scande3** [comment]
@gvasold - can you make a pull request? Or, if you prefer, I could do one for it?
