### ISSUE TITLE
confusing documentation around --libkdu option for installation?

### ISSUE THREAD

**Issue by ghukill** [loris-imageserver/loris#179]
We had trouble getting Loris to transform .jp2 files, and after some digging and environment printing during runtime, determined it was a path issue. 

The install option flags for setup.py state:
`--libkdu     Path to libkdu.so [Default: /usr/local/lib/libkdu.so]`

Which suggested to us, that given our installation of Kakadu which has the lib file `libkdu_v77R.so`, we should set that flag as, `/usr/local/lib/libkdu_v77R.so`, as the default contains the .so file explicitly.  This resulted in .jp2 files not processing.  When we removed the file from the option and used simply `/usr/local/lib` it works.

What made this confusing, at least for us, was the `--kdu-expand` option has similar language with the binary file included:
`--kdu-expand      Path to the Kakadu executable [Default: /usr/local/bin/kdu_expand]`,
but **does** actually require the binary to be included (e.g. `/usr/local/bin/kdu_expand`).  

Just thought some clarification in the install flags might help.  Otherwise, so far we're pleased as punch with Loris!  Thanks for making it available.

**Comment by jpstroop** [comment]
@ghukill , thanks for the note. This had gone unnoticed for a very long time, and now you're the second person to mention it in a week (/cc @terrellt)! I just pushed up a quick update. I'm glad you're happy w/ Loris!

**Comment by tangfucius** [comment]
Had the same problem and this helped solve it for me. But [documentation](https://github.com/loris-imageserver/loris/blob/development/doc/setup.md) for setup.py still looks the same? At least I certainly couldn't tell from the documentation that I have to change the config file to this after installing to get it working on jp2 images. Thanks for making this available - loris is the first IIIF server that I managed to get working!

**Comment by jpstroop** [comment]
It looks like the default is still wrong:
https://github.com/loris-imageserver/loris/blob/development/setup.py#L27
I thought this was fixed! Fix coming..
