### ISSUE TITLE
500 error / circular symlinks

### ISSUE THREAD

**Issue by rlskoeser** [loris-imageserver/loris#187]
I'm occasionally seeing 500 errors with circular symlinks for images that at other times have worked fine.

Example output from loris:

```
Server Side Error: [Errno 40] Too many levels of symbolic links: u'/u/data/loris/cache/qasfedora:readux:px393/full/!100,100/0/default.png' 

This is likely a permissions problem, though it's
possible that there was a problem with the source file
(/u/data/loris/cache/qasfedora/readux/16/7c3/8ba/44b/dd0/f1e/b15/b98/f5b/b8b/d30/loris_cache.jp2). (500)
```

The original cache file looks fine, but the resized version appears to be a symlink to itself:

```
ls -l '/u/data/loris/cache/qasfedora:readux:px393/full/!100,100/0/default.png'
lrwxrwxrwx 1 loris apache 70 Nov 10 10:20 /u/data/loris/cache/qasfedora:readux:px393/full/!100,100/0/default.png -> /u/data/loris/cache/qasfedora:readux:px393/full/!100,100/0/default.png
```

I may be able to look into this if someone can provide some suggestions of where in the code to start looking or some ideas on what the problem might be.  As I said, it's sporadic because these kinds of images display fine most of the time.

**Comment by jpstroop** [comment]
I can't look at the moment, but it's either the code in the image cache or
the code in the webapp that makes the image that makes these symlinks. The
idea is to store the image in the cache at a path based on the canonical
request URI, and then link to it from a path based on the actual request.

My guess is that there's a bug in the condition that checks whether or not
the request was made using the canonical syntax.

It's a minor performance enhancement, and I wouldn't be against removing it
altogether. It's not the first time it's caused trouble.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by rlskoeser** [comment]
As you'll see, I've got a pull request with a preliminary fix to prevent creating circular symlinks, but I haven't figured out yet what could cause a canonical cache path to be generated incorrectly.  I'm guessing maybe it's in the parameters code; is it possible that the size parameter could fail to get the image size under certain circumstances and thus not be able to calculate the normalized form correctly? 

At a higher level, I'm not understanding why images are stored the way they are.  Is there anything in the project or code documentation that explains the cache file layout and rationale?  In particular, if you can generate a canonical format for a given image request, why not _always_ use that path instead of using the non-canonical format and creating a link?  Is there an important efficiency gained in storing files in the cache using the same format they are accessed via web URI, or would it be reasonable to switch to something else, like a hash-based / pair-tree style directory layout?  

Another thought: if you stick with the current cache layout, wouldn't it make more sense to use the canonical image path for the actual image, and then make links for any equivalent non-canonical paths? (It seems like it would be possible to have multiple non-canonical paths resolve to the same canonical one...)

**Comment by jpstroop** [comment]
> why not always use that path instead of using the non-canonical format and creating a link?

I agree; or just always cache at the canonical path and  dump the symlink behavior altogether, as I typed with my thumbs yesterday.

I think all of the relevant code is here: https://github.com/loris-imageserver/loris/blob/development/loris/img.py#L217-L232
