### ISSUE TITLE
Serving Image from Fedora

### ISSUE THREAD

**Issue by lfarrell** [loris-imageserver/loris#196]
This may not be the right place to ask this, but I was wondering how to put in a UUID to pull a Img/JP2 stream from Fedora? I have the HTTP Resolver suffix & prefix in place, but I'm not sure how to pass the UUID from loris to Fedora.

Thanks,

Dean

**Comment by jpstroop** [comment]
I believe it should just work, the resolver code builds URL and makes the
request. Does that not work? Looping in @scande3 in case there's something
more specific you should know. If you're seeing errors, can you post any
additional information?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by scande3** [comment]
I'm assuming he is using Fedora 4 Commons which I've never tested against. It should work similar to a PID though? Essentially: you construct a url with the identifier and then your parameters. For example, given a pid of "commonwealth:wh246s56b", it then can resolve as follows on our server:

https://iiif.digitalcommonwealth.org/commonwealth:wh246s56b/100,450,3168,1645/570,/0/default.jpg

Of course, if you are using Sufia, it uses a Noid Minter that obfuscates the actual object identifier. You may need to work around that? Or can you give an example of what your settings and UUID look like exactly?

Thanks!

**Comment by lfarrell** [comment]
I'm working with Fedora 3.8. At the moment I'm passing a URL like this http://localhost:5004/uuid:c18d73e0-3b36-4a9a-a30c-ee3576f28cd7, which gives the following: Not Found: could not resolve identifier: uuid%3Ac18d73e0-3b36-4a9a-a30c-ee3576f28cd7  (404), though if I look in my repo there's an image with that UUID.

Thanks,
Dean

**Comment by scande3** [comment]
In theory, there should be no issues then. Can you share what is exactly in your loris2.conf for the SimpleHTTPResolver exactly? Are you able to look at any server logs to see which part is returning the 404?

Something like the following from /var/log/loris/loris.log:
2015-07-30 10:23:24,348 (urllib3.connectionpool) [INFO]: Starting new HTTPS connection (1): fedoradev.bpl.org

Something like the following in /var/log/apache2/access.log:
74.11.69.126 - - [08/Dec/2015:09:31:30 -0500] "GET /commonwealth%3A6682zb81t/0,0,4892,3900/612,/0/default.jpg HTTP/1.1" 200 114470 "https://www.digitalcommonwealth.org/search/commonwealth:6682zb80j" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

**Comment by scande3** [comment]
(may also be worthwhile to look in "other_vhosts_access.log" if that exists in the apache2 log directory)

**Comment by lfarrell** [comment]
Here's the loris HTTP setup:

impl = 'loris.resolver.SimpleHTTPResolver'
source_prefix='https://localhost:8443/fedora/objects/'
source_suffix='/datastreams/IMAGE_JP2000/content'
cache_root='/usr/local/share/images/loris'
head_resolvable=True
default_format='jp2'
user='fedoraUsername'
pw='fedoraPassword'

There doesn't seem to be anything in /var/log/loris/ directory. At the moment I'm using the webapp script that comes with loris to test out serving images. Here's a request from that:

2015-12-08 14:56:03,532 (webapp) [DEBUG]: request_type: info
2015-12-08 14:56:03,532 (werkzeug) [INFO]: 127.0.0.1 - - [08/Dec/2015 14:56:03] "GET /uuid:c18d73e0-3b36-4a9a-a30c-ee3576f28cd7 HTTP/1.1" 404 -
2015-12-09 08:39:54,750 (webapp) [DEBUG]: /uuid:c18d73e0-3b36-4a9a-a30c-ee3576f28cd7
2015-12-09 08:39:54,751 (webapp) [DEBUG]: _dissect_uri ident: uuid%3Ac18d73e0-3b36-4a9a-a30c-ee3576f28cd7
2015-12-09 08:39:54,751 (webapp) [DEBUG]: _dissect_uri params: None
2015-12-09 08:39:54,752 (webapp) [DEBUG]: base_uri_from_request: http://localhost:5004/uuid%3Ac18d73e0-3b36-4a9a-a30c-ee3576f28cd7

**Comment by scande3** [comment]
Ah. Better if you can test it in Apache as I don't think I've ever used it that way. I believe the values are hard-coded for the default resolver implementation in the webapp script rather than what is configured? (Could be wrong about this - @jpstroop ?). If I'm not correct about that, can research it tomorrow to see how that method ends up working.

**Comment by jpstroop** [comment]
Ahh, yes, that absolutely correct!

If you really don't want to hassle with setting up Apache yet, you could tinker with [these lines](https://github.com/loris-imageserver/loris/blob/6dc5c1b1c51859e97242f68060ac366a6d267a8d/loris/webapp.py#L38-L58) to have the dev server load a different resolver. Sort of like @scande3 does in the [tests](https://github.com/loris-imageserver/loris/blob/development/tests/resolver_t.py#L95-L106).

**Comment by lfarrell** [comment]
Semi related is there a straightforward way to uninstall loris if I want to start fresh?

**Comment by lfarrell** [comment]
Got everything funneling through Apache now. Have you all ever had an issue with the returned info.json file being blank?

**Comment by jpstroop** [comment]
> Got everything funneling through Apache now. Have you all ever had an issue with the returned info.json file being blank?

Hmm...only when there's an error somewhere further upstream (i.e. with the source image or in the application). Is there anything in your Apache logs that might provide a clue? If you want to share the source image with me privately I'd be happy to have a look in the next few days.

**Comment by lfarrell** [comment]
The issue turned out to be the img root directories weren't on the file
system. So, I'm guessing there was nowhere to put the images. Once they
were added it would return a populated info.json

/usr/local/share/images

/usr/local/share/images/loris

**Comment by lfarrell** [comment]
Is there a way to avoid multiple head requests to fedora?

It seems to do something like this:
http://localhost/loris/uuid:c18d73e0-3b36-4a9a-a30c-ee3576f28cd7/info.json/datastreams/IMAGE_JP2000/content
This always gives a 500 error.

Depending on how we access it on our system it sometimes then tries again
with the info.json bit left out
http://localhost/loris/uuid:c18d73e0-3b36-4a9a-a30c-ee3576f28cd7/datastreams/IMAGE_JP2000/content

This returns a 200.

Thanks,

Dean

**Comment by scherztc** [comment]
Helpful thread.  Image cache directory permissions were giving me hang ups when going from sandbox to production.  Thanks.
