### ISSUE TITLE
Cannot generate info.json for some JP2 images.

### ISSUE THREAD

**Issue by scande3** [loris-imageserver/loris#209]
Hiya,

I'm unable to generate a info.json response for certain JP2 images. One example of this behavior is the following image that will just hang endlessly: http://fedoradev.bpl.org/fedora/objects/bpl-dev:5h73q433b/datastreams/accessMaster/content

There are no problems with 99% of our JP2 images but we are up to five known cases of this odd behavior. I've tried many things to resolve this... from switching out Kakadu with OpenJP2 to generating the JP2 derivative via different means. Nothing has made any different and I am running the latest commit of the development loris branch now.

So... any ideas what might cause this? Or can you point me to where this information is calculated and how I might test what libraries it might be using to generate its info.json response?

Thanks!

**Comment by jpstroop** [comment]
Hey Steven,
That seems strange...hanging on info isn't something I can remember seeing, but I certainly believe you.

There no libraries with Python bindings that can pull all of this info, so it happens natively: 

https://github.com/loris-imageserver/loris/blob/development/loris/img_info.py#L137

It's tough to parse w/o a copy of the JP2 spec, but it's been pretty reliable for a long time. The only case I know it doesn't cover is tiles that _contain_ precincts--you can have tiles or precincts, which is the 99.999% use case, but not both, and and I believe code would just ignore the tiles in this case, so it seems unlikely that that's the cause.

If you want to debug with the webapp out of the way, there's a script [here](https://github.com/loris-imageserver/loris/blob/development/bin/iiif_img_info) that will just dump the info.json to stdout. That might be a good place to start.

The script isn't very fancy; it doesn't get installed by setup.py or anything. just cd into bin and do `./iiif_img_info [-v] path/to/an/image.fmt` (as it says).

I'm happy to have a look as well if you have a way to share the TIFF (presumably) from which you're generating the JP2.

**Comment by scande3** [comment]
@jpstroop -> It seems like even the JP2 may have been inaccessible as it appears I forgot our dev fedora doesn't resolve externally. So:

Original TIF File: https://fedora.digitalcommonwealth.org/fedora/objects/commonwealth:wm118r832/datastreams/productionMaster/content

Generated JP2 Derivative: https://fedora.digitalcommonwealth.org/fedora/objects/commonwealth:wm118r832/datastreams/accessMaster/content

If you could try it on your machine, would appreciate it. Will also try your script. Thanks!

**Comment by scande3** [comment]
Output of that iiif_img_info script:

> DEBUG:loris.img_info:Source Format: jp2
> DEBUG:loris.img_info:Source File Path: /home/hydra/loris/bin/content.jp2
> DEBUG:loris.img_info:Identifier: file:///home/hydra/loris/bin/content.jp2
> DEBUG:loris.img_info:Extracting info from JP2 file.
> DEBUG:loris.img_info:width: 1785553249
> DEBUG:loris.img_info:height: 1852402536
> unpack requires a string argument of length 1

It just exists back to console after that last message that seems to indicate an error. On other derivatives, this script just outputs the info.json hash at the end. Can try with more debugging a bit later to see what command it stops at...

**Comment by scande3** [comment]
The error occurs at the following line:
https://github.com/loris-imageserver/loris/blob/eaad26863d4873c799973442f5f27482da4eb223/loris/img_info.py#L165

I'm unsure what exactly this code is doing. So any guidance on what might be up that causes this image to fail is appreciated. Thanks!

**Comment by jpstroop** [comment]
Hmm. The while loop is a sliding window through the header looking for 
the string 'colr' which marks the beginning of of the Color 
specification box of the JP2. Need to open you JP2 in a hex editor to 
see if I can figure out why that's not working. I will try my best to 
get to it tomorrow, but I'm not sure I'll be able to get to it until 
next week.

**Comment by scande3** [comment]
@jpstroop Whenever you could is appreciated. If you are unable to, I can research into it, but would take time as haven't dealt much with how files are represented information is represented within its binary data. Thank you!

**Comment by scande3** [comment]
I spent a few hours debugging this today (learned a bit about reading the JP2 header) and it isn't a loris issue. Rather it deals with a case of a compressed TIF file that kakadu doesn't support with its provided binary tools. In these rare cases, I fallback to using MiniMagick in my code, and a feature in that seems to be busted.

Essentially the format to load an image with options set as exists in their [README under combine options](https://github.com/minimagick/minimagick/blob/master/README.md) no longer functions. As such, it generates a bad jp2 image file. So essentially replacing:

`jp2_img = MiniMagick::Image.read(self.productionMaster.content) do |b|`
`b.format "jp2"`
`end`

with the less efficient from testing in the past due to not doing the transformation on load:

`jp2_img = MiniMagick::Image.read(self.productionMaster.content)` 
`jp2_img.format 'jp2'` 

So MiniMagick ignored the format option that used to work with that syntax and was just rewriting the tif file content with a jp2 extension. Then when I try to open it in a graphic program, it ignored the file extension and figured out to load it as a tif so that I didn't notice an error there.

I'll likely do a pull request later that sets a maximum byte read size on the header and raises an error of an incorrect jp2 file format rather than just continuing to read through all the file contents and then giving a read error? Thanks!

**Comment by jpstroop** [comment]
Stephen,
That's great--I'm sorry I wasn't able to get to look at it. The IIIF conference ate my whole week last week. I agree that this would be a good error to raise. There was an issue buried somewhere about using magic to characterize the file, and then choosing the appropriate extraction function and transformer based on that info...seems sort of relevant to this, but I was always worried about the performance hit.

**Comment by bcail** [comment]
I think this can be closed now, with PR #256 being merged.

**Comment by scande3** [comment]
Closing as that PR does seem to test to ensure this doesn't occur.
