### ISSUE TITLE
In doc/deployment.md the following sections are not in the loris.conf file...

### ISSUE THREAD

**Issue by sdellis** [loris-imageserver/loris#21]
Daemon Mode >> Adjust 
- under [handler_err] and [handler_out] set args to reflect the correct log dir, .e.g. something like args=('/var/log/loris/loris.err', 'midnight', 1, 14)

Is that something that should be there, or was it taken out?

**Comment by sdellis** [comment]
Looks like they are in the logging.conf file... doc should be updated

**Comment by jpstroop** [comment]
Sorry, it was split into a separate file...I've been working to make the 
code more modular over the last week. There are a lot more, but smaller 
and more readable, files. I thought I'd managed to keep the docs up to 
date, but missed this one.
