### ISSUE TITLE
Generally needs to be easier to get working

### ISSUE THREAD

**Issue by sdellis** [loris-imageserver/loris#22]
While attempting to integrate loris in the image browser, noticed a lot has changed since I last used it.  Someone with basic skills should be able to get this to roll over in under an hour woking with basic test images.  Convention over configuration.  For example, found this in the loris/resolver.py file:

SRC_IMG_ROOT='/home/jstroop/workspace/loris/test_img'

... shouldn't this be in a conf file somewhere?  And I would argue for a single conf file... even though it may get long, convention should be that most people don't have to change but a few values.

**Comment by jpstroop** [comment]
> shouldn't this be in a conf file somewhere?
> My opinion is no. Anyone deploying this in a different environment is 
> likely going to have to re-implement this function to make their 
> identifiers resolve to paths to images; they might depend on database 
> queries, for example, in which case the constant that's in the file now 
> wouldn't make sense, and therefore it doesn't make sense in the 
> application's main config file. The resolver could have its own conf 
> file, but that seems like overkill.

I put a more generic path in the file that's on github.
