### ISSUE TITLE
Creating tiles on demande

### ISSUE THREAD

**Issue by FPaquette** [loris-imageserver/loris#224]
Hi,
 Our institution is looking to replace our old images server & viewer, we are pretty much set on the viewer we would be using but we are still looking for an images server. Loris is one of the servers we are considering. Could you tell me if it's possible to create tiles images on demand and not beforehand? I am not seeing anything about it in the documentation but I would like to be sure. 

Thanks!

**Comment by jpstroop** [comment]
Yes, Loris creates tiles on the fly, and then caches them on the file
system for future requests.
