### ISSUE TITLE
What is the contract on a Resolver.is_resolvable method?

### ISSUE THREAD

**Issue by jrhoads** [loris-imageserver/loris#227]
Specifically, I'm curious about its interaction with caching.
If something is found in the file-cache (as opposed to the info-cache) should that be considered resolvable, or should we look back to the source.

This is analogous to the Caching Modes of Operation from the Cantaloupe Image server
https://medusa-project.github.io/cantaloupe/manual/3.0/caching.html#Modes%20of%20Operation

**Comment by jpstroop** [comment]
First, let me say that I hate `is_resolvable` and it's only necessary for the reasons I explained here: https://github.com/loris-imageserver/loris/pull/219#issuecomment-224435807. To me it was intended to be against the source, e.g. via a HEAD request or `os.path.isfile` and the cache should be opaque, but I _think_ @scande3's Fedora resolver just always returns True, so it's effectively being skipped.

I'd really like to see that method, and caching, and, frankly, WSGI be gone from Loris some day. :imp:

**Comment by jrhoads** [comment]
Thanks for your response Jon.

I understand.  I'd like to see Loris as a leaner package as well.  Specifically I would like to be able to drop in to whichever application server (django/flask/tornado) is appropriate at the time.

For now I will consider the contract for is_resolvable to check the source
