### ISSUE TITLE
requests 2.6 does not have pyopenssl

### ISSUE THREAD

**Issue by azaroth42** [loris-imageserver/loris#230]
Upgraded with pip to 2.10 and install proceeded.

Previously got:

```
-bash-4.2$ python ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 225, in <module>
    __import__(d[2], fromlist=[''])
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 75, in load_module
    __import__(name)
ValueError: Empty module name
```

**Comment by jpstroop** [comment]
Interesting. We're running on HTTPS here as haven't seen that. PR to update `requirements.txt` and `setup.py`?

**Comment by andjsmit** [comment]
Got the same error today on a fresh install of RHEL 7. Wasn't sure what upgraded was being referred to at first. Finally saw the light. Fix for me was `pip install --upgrade requests`. Setup completed afterwards.

**Comment by azaroth42** [comment]
It seems to be fixed in more recent versions of requests.  Can we unpin it?

**Comment by bcail** [comment]
Seems like it'd be fine to move to the latest version of requests. Are you able to submit a PR?

**Comment by azaroth42** [comment]
Sure :)
