### ISSUE TITLE
image converter to iiif format

### ISSUE THREAD

**Issue by xcompass** [loris-imageserver/loris#231]
Does this come with a tool to convert images (jpg/png) to iiif format? If yes, where is it and how to use it? I couldn't find any doc in the repo mentioning this.

If not, is there an open source tool for this purpose? Thanks.

**Comment by jpstroop** [comment]
@xcompass: Thanks for your interest in Loris and IIIF!

The [IIIF Image API](http://iiif.io/api/image/2.1/) defines a protocol for accessing images and regions of images at arbitrary sizes, as well as some other lightweight manipulations, regardless of the format (e.g. jpg, png, jp2, tif) of the images you have available--in fact the specification very purposefully does not discuss the format of source images at all.

Loris will take png, tif, jpg, and jp2 as the source format, and most other IIIF-compliant servers will at least take jp2 and tif, with jp2 generally being the best-performing of these by far.

If I've misunderstood your question, and you're just looking to pre-generate a bunch of tiles to work with a deep zoom viewer, I'd suggest that you look at [this utility](https://github.com/zimeon/iiif/blob/master/iiif_static.py) that @zimeon made to do just that.

I hope this is helpful.

**Comment by jpstroop** [comment]
@xcompass May I close this issue, or would you like further clarification?

**Comment by xcompass** [comment]
Thanks @jpstroop. That answers my question.
