### ISSUE TITLE
changing src_img_root wont work in centos6

### ISSUE THREAD

**Issue by tomturner123** [loris-imageserver/loris#233]
Hi. I've been having a go at getting loris working with centos6. I have successfully managed to load some images but only when the src_img_root folder starts with /usr/... any other directory and I get a "Not Found: could not resolve identifier: ... (404)" error. I tried using a symlink within the /usr directory but it generates the same error. Ive checked the apache logs which dont show anything new. My /var/log/loris2 directory is empty (no doubt because I havnt set it up properly). If someone could point me in the right direction that would be really helpful. Thanks

**Comment by tomturner123** [comment]
disabling SELinux solved the problem!

**Comment by jpstroop** [comment]
That's the solution to _many_ problems :wink:, and was the first thing I was going to suggest when I saw your issue this morning. @mmcclimon added some documentation a couple of years ago [here](https://github.com/loris-imageserver/loris/blob/development/doc/redhat-7-install.md#selinux-module) that might be helpful is you need to keep SELinux enabled.

**Comment by jpstroop** [comment]
Otherwise, shall we close this issue?

**Comment by tomturner123** [comment]
Thanks for your reply. I had tried the to implement the notes you linked to but clearly not very successfully. For my use Im happy to leave SELinux disabled. Thanks

**Comment by jpstroop** [comment]
No problem. :-)
