### ISSUE TITLE
TemplateHTTPResolver does not call its parent class initializer correctly

### ISSUE THREAD

**Issue by peichman-umd** [loris-imageserver/loris#239]
The TemplateHTTPResolver in resolver.py does not call its parent initializer correctly. Instead, it calls `super(SimpleHTTPResolver, self).__init__`, which calls its _grandparent_ initializer (i.e., AbstractResolver). As such, it does not get intialized as a SimpleHTTPResolver, and there is duplicated code in the initializer that could be eliminated.

**Comment by peichman-umd** [comment]
Tagging @rlskoeser and @ghukill as they appear the be the main contributors on the TemplateHTTPResolver.

**Comment by jpstroop** [comment]
Closed by #240
