### ISSUE TITLE
ETag caching

### ISSUE THREAD

**Issue by scossu** [loris-imageserver/loris#280]
I looked at https://github.com/loris-imageserver/loris/issues/148 and it may be a reasonable solution to ensure that the Loris cache is up-to-date. However, that requires the data provider, which likely knows nothing about Loris, actively triggering the purge action. 

In our particular implementation we are pulling source images from Fedora 4 which supports ETags and `If-None-Match` headers (https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.26). I am wondering if implementing an ETag-based caching mechanism would be the most efficient and reliable way to cache source images, and how this could be achieved. 

The way I am thinking this would be relying on a key-value store containing pairs of identifiers and known ETags. If an ETag is present in the store for the UID of a particular requested image, Loris would send the HTTP server a `If-None-Match` header and only retrieve the binary if the response code is `2xx` (i.e. the binary has effectively changed from the cached one). 

A purge function could be implemented separately, in this case Loris would have to delete the UID-ETag pair with the cached image in order to be able to fetch the content again. 

On the other hand, it would be even nicer if Loris supported ETags and `If-None-Match` as a server, making caching of tiles and derivatives much more efficient. I don't know however how this may intersect with IIIF specs. 

Thoughts? I may be able to spec out the required effort to implement this, and maybe contribute code in case it proves to be a valid route.

**Comment by jpstroop** [comment]
Off the top of my head, probably the easiest way to make an etag would be to hash a concatenation of the request URI (or at least the IIIF params - `/full/full/0/default.jpg` or whatever) and the last modified date of the source file.

**Comment by jpstroop** [comment]
...but that would probably change the resolver API, as the last-modified date might not be reliable if you just looked at what ultimately winds up on disk.

**Comment by scossu** [comment]
I realize that I raised two separate, completely independent issues here—a) producing ETags and supporting the `If-None-Match` header for clients, and b) using ETags *specifically in the HTTP resolver* to manage the cache of source images. Would it be better to split this issue up?

**Comment by jpstroop** [comment]
I think so. Both seem possible, but the the resolver one seems easier

**Comment by scossu** [comment]
Splitting up into #281 and #282.
