### ISSUE TITLE
[Support Request] Integrating with Newrelic Python Agent?

### ISSUE THREAD

**Issue by bboro** [loris-imageserver/loris#285]
I'm looking for someone who has tried and succeeded to integrate Newrelic's Python Agent with Loris. 

Newrelic Documentation: https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-installation

Newrelic is a server/application monitoring service (you can create a free account with them with no obligation to buy anything), then you can install various agents to monitor various apps. Such as the PHP agent for monitoring most PHP applications like Drupal and Wordpress, Java agent for Tomcat etc. I've tried installing their Python agent and integrate it with Loris but I have failed to get any data back.

I've installed the Python agent on my server using sudo pip to install globally, and then I created the config file newrelic.ini with my license key using the newrelic-admin script. After that I've edited the loris source loris/webapp.py, and added their imports at the very top:

```
  #!/usr/bin/env python
  #-*- coding: utf-8 -*-
  '''
  webapp.py
  =========
  Implements IIIF 2.0 <http://iiif.io/api/image/2.0/> level 2
  '''
  # from ConfigParser import RawConfigParser
+ import newrelic.agent
+ newrelic.agent.initialize('/path/to/newrelic.ini')
  from configobj import ConfigObj
  from datetime import datetime
  from decimal import getcontext
```

I then re-installed Loris using setup.py on my server, from the edited source. Restarted apache, and I can still get images output from Loris (not cached as I'm requesting different rotations everytime).

According to the documentation, that's all that's needed to get data back from most apps. But after a day of waiting, I'm still not getting anything, not even the application's name in Newrelic.

Supposedly, newrelic-admin script is also a wrapper which you can use to start wsgi applications, but Loris uses Apache's mod_wsgi so the docs say I have to do manual integration.

Any pointers greatly appreciated.

**Comment by bcail** [comment]
I'm not familiar with Newrelic, but you're not required to use mod_wsgi with loris. We use Phusion Passenger to serve our loris application. Loris is just a wsgi app that can be served however you're comfortable serving other wsgi apps. Also, you're not required to use setup.py - we don't use that either. We just put the loris code in a passenger app root and set the paths up correctly, and it works fine.

See https://library.brown.edu/DigitalTechnologies/loris-image-server/.

Hope that helps.
