### ISSUE TITLE
undefined variable in resolver.py

### ISSUE THREAD

**Issue by mrdale1958** [loris-imageserver/loris#295]
Line 238 (in _web_request_url) says
Bad URL request at %s for identifier: %s.' % (source_url, ident)
but source_url is undefined.  I suspect it should just be url

The result is a server error instead of a useful error message

**Comment by jpstroop** [comment]
Good catch! I'm sure you're correct. Want to make a PR?

**Comment by jpstroop** [comment]
Closed with #296
