### ISSUE TITLE
TypeError: 'unicode' object does not support item assignment

### ISSUE THREAD

**Issue by regisrob** [loris-imageserver/loris#30]
Hello Jon,

I have been struggling with Loris for a few days and I think it would be interesting to give you some feedback.
I started with the loris-master version and tried to test it with a sample jp2 file. Finally I obtained a "502 Proxy Error. Reason: Error reading from remote server" (maybe from the reverse proxy ? no idea about that...).
So I decided to test Simeon's fork of Loris (I thought it would be easier to manipulate static images as source), but I did not manage to install it.
Then I saw the latest developments you made this week and tried again. I encountered some problems with setup.py (which is not yet updated to take into account changes in etc/loris.conf), so I had to install it manually. Now I think the setup is done but I am facing a bug.

Here is the final error from Apache logs. I posted another issue that give you all the configuration and environment details (it could be useful to other python newbies like me in the future).

```
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38] mod_wsgi (pid=10518): Exception occurred processing WSGI script '/var/www/loris/loris.wsgi'.
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38] Traceback (most recent call last):
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38]   File "/usr/local/loris/lib/python2.7/site-packages/Loris-0.1.0dev-py2.7.egg/loris/webapp.py", line 215, in __call__
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38]     return self.wsgi_app(environ, start_response)
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38]   File "/usr/local/loris/lib/python2.7/site-packages/Loris-0.1.0dev-py2.7.egg/loris/webapp.py", line 206, in wsgi_app
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38]     response = self.dispatch_request(request)
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38]   File "/usr/local/loris/lib/python2.7/site-packages/Loris-0.1.0dev-py2.7.egg/loris/webapp.py", line 212, in dispatch_request
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38]     return getattr(self, 'get_'+endpoint)(request, **values)
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38]   File "/usr/local/loris/lib/python2.7/site-packages/Loris-0.1.0dev-py2.7.egg/loris/webapp.py", line 371, in get_img
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38]     headers['Link']['profile'] = constants.COMPLIANCE
[Fri Jun 28 12:46:04 2013] [error] [client 10.14.1.38] TypeError: 'unicode' object does not support item assignment
```

**Comment by jpstroop** [comment]
Régis,
Thanks for trying out Loris! I've been squeezing in work on what more or less amounts to a complete rewrite of Loris since our meeting in Paris last month. You're right, `setup.py` is out of date; I was hoping to work on it this afternoon  in fact, after I finish the new README, but I may run out of time.

I wasn't able to reproduce your bug until I tried upgrading Werkzeug from 0.8.1 to 0.8.3, and then it showed up. In the past, Werkzeug seemed to call str() on the [RelatedLinkesHeader](https://github.com/pulibrary/loris/blob/development/loris/webapp.py#L546) instance for me, but now I have to do it explicitly. Tests are passing again and I just pushed this fix to development.

I'll leave this open until I hear from you.

Best,
Jon

**Comment by regisrob** [comment]
Thank you very much Jon. Right now I'm happy to see the very first Biblissima IIIF compliant image ! The fix to webapp.py did the job. 
Actually I'm using the last version of Werkzeug (0.9.1). I will post another comment with some configuration details about my own deployment of Loris. It could be useful in case I notice new bugs later. Next week I will run some deeper tests with various examples and put a viewer on top of it (as a demo for Biblissima partners). Likely I will reuse your OpenSeadragon demo.
Thanks for debbuging and the new README (very useful for me !).

Best,
Régis

**Comment by regisrob** [comment]
I gathered below some details about the environment in which Loris is running on Biblissima server, and the main setup/configuration steps I followed. It could be useful to people (like me) who are not Python developers and are using Debian.      

---
- OS : **Debian Squeeze 2.6.32-5-amd64**

---
- **Apache/2.2.16 (Debian)**

```
#/usr/sbin/apachectl -V
Server version: Apache/2.2.16 (Debian)
Server built:   Mar  3 2013 12:09:44
Server's Module Magic Number: 20051115:24
Server loaded:  APR 1.4.2, APR-Util 1.3.9
Compiled using: APR 1.4.2, APR-Util 1.3.9
Architecture:   64-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="/var/run/apache2/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"
```

---
- **Python** :
  - System version (package from Debian repositories) : Python 2.6.6
  - Virtualenv version (for Loris) : **Python 2.7.3**.<br />
    Built from source with : ./configure --enable-shared --with-threads
  - Install folders :<br />
    /usr/local/lib/python2.7<br />
    /usr/local/bin/python2.7

---

Additionnal dependencies :
- **ImageMagick** : installed from Debian repositories

```
# convert -v
Version: ImageMagick 6.6.0-4 2012-05-02 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2010 ImageMagick Studio LLC
Features: OpenMP
```
- **Kakadu** : 
  - Install locations : <br />
    /usr/local/lib/libkdu_v72R.so<br />
    /usr/local/bin/kdu_expand
- **Python Imaging (PIL)** : built from source for Python 2.7 (deb package python-imaging is for Python 2.5 and 2.6 ; see "apt-cache show python-imaging")<br />
  source : wget http://effbot.org/media/downloads/Imaging-1.1.7.tar.gz<br />
  Install folder : /usr/local/loris/lib/python2.7/site-packages/PIL

```
--------------------------------------------------------------------
PIL 1.1.7 SETUP SUMMARY
--------------------------------------------------------------------
version       1.1.7
platform      linux2 2.7.3 (default, Jun 24 2013, 22:45:52)
              [GCC 4.4.5]
--------------------------------------------------------------------
*** TKINTER support not available
--- JPEG support available
--- ZLIB (PNG/ZIP) support available
--- FREETYPE2 support available
*** LITTLECMS support not available
--------------------------------------------------------------------
```
- **Debian packages** from repositories : 

```
libjpeg62 libjpeg62-dev libjpeg8 libfreetype6 libfreetype6-dev zlib1g zlib1g-dev
```

---
- **mod_wsgi 3.4** : compiled from source for Python2.7 with : ./configure --with-apxs=/usr/bin/apxs2 --with-python=/usr/local/loris/bin/python2.7<br />
  Library location : /usr/lib/apache2/modules/mod_wsgi.so

```
ldd /usr/lib/apache2/modules/mod_wsgi.so 
    linux-vdso.so.1 =>  (0x00007fff8118c000)
    libpython2.7.so.1.0 => /usr/local/lib/libpython2.7.so.1.0 (0x00007fea24895000)
    libpthread.so.0 => /lib/libpthread.so.0 (0x00007fea24671000)
    libdl.so.2 => /lib/libdl.so.2 (0x00007fea2446c000)
    libutil.so.1 => /lib/libutil.so.1 (0x00007fea24269000)
    libm.so.6 => /lib/libm.so.6 (0x00007fea23fe7000)
    libc.so.6 => /lib/libc.so.6 (0x00007fea23c84000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fea24ea1000)
```

---
- **Loris** : 
  - Project's virtualenv : /usr/local/loris
  - Manual installation, see commands list below :

```
# sudo mkdir /var/www/loris /tmp/loris /tmp/loris/tmp /tmp/loris/cache /tmp/loris/cache/img /tmp/loris/cache/links /tmp/loris/cache/info /etc/loris /tmp/loris/tmp/jp2 /var/log/loris
# sudo cp -r www/* /var/www/loris
# sudo cp -r etc/* /etc/loris
# sudo chown -R loris:loris /var/www/loris /tmp/loris /tmp/loris/tmp /tmp/loris/cache /tmp/loris/cache/img /tmp/loris/cache/links /tmp/loris/cache/info /etc/loris /tmp/loris/tmp/jp2 /var/log/loris
# sudo nano /var/www/loris/loris.wsgi
# sudo nano /etc/apache2/sites-available/interne
# sudo /etc/init.d/apache2 reload
```

Some adjustments made in loris.wsgi :

```
import site
site.addsitedir('/usr/local/loris/lib/python2.7/site-packages')
import sys
sys.path.append('/usr/local/loris/lib/python2.7/site-packages/Loris-0.1.0dev-py2.7.egg/loris')
from webapp import create_app
application = create_app()
```

Default image root folder : /usr/local/share/images

Content list of "/usr/local/loris/bin/python2.7/site-packages" :

```
Jinja2-2.7-py2.7.egg-info
Loris-0.1.0dev-py2.7.egg
MarkupSafe-0.18-py2.7.egg-info
PIL
PIL.pth
Werkzeug-0.9.1-py2.7.egg-info
easy-install.pth
jinja2
markupsafe
pip-1.3.1-py2.7.egg
setuptools-0.6c11-py2.7.egg
setuptools-0.7.4-py2.7.egg
setuptools.pth
werkzeug
```

---
- Check install : see http://code.google.com/p/modwsgi/wiki/CheckingYourInstallation

```
sys.version = '2.7.3 (default, Jun 26 2013, 23:21:09) \n[GCC 4.4.5]'
sys.prefix = '/usr/local'
sys.path = ['/usr/local/loris/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg', '/usr/local/loris/lib/python2.7/site-packages/setuptools-0.7.4-py2.7.egg', '/usr/local/loris/lib/python2.7/site-packages/Loris-0.1.0dev-py2.7.egg', '/usr/local/loris/lib/python2.7/site-packages', '/usr/local/loris/lib/python2.7/site-packages/PIL', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux2', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages']
mod_wsgi.process_group = 'loris' (=> daemon mode)
mod_wsgi.application_group = ''
wsgi.multithread = True
```
