### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by rogerhoward** [loris-imageserver/loris#324]
I'm interested in seeing loris support Python 3 (3.5+) and am willing to tackle this, having quite a bit of experience over the past few years migrating old projects forward. Apologies if this has already been discussed and ruled out - I searched old issues without finding anything.

Before I embark on this, I'd like some input, or certainly get any *over my dead body* comments out of the way first. There are several approaches this could take, in no particular order:

1. Update to Python 3-only - this is easiest on the person doing the porting, but probably a non-starter as it would force all current users to update their environments.
2. Update to Py2/3-compatible code, using `six` where useful to abstract some of the more annoying differences. This is the route most projects I'm familiar with have taken - eg., Django. This would allow most current deployments to update to a new Python 3-compatible version without having to update to Python 3.
3. Update to Py2/3-compatible code without using `six` - avoids a dependency, but I don't think this gains much, ends up reimplementing six but worse.

Reviewing the current project, the majority of changes are pretty straightforward: dealing with string vs. unicode literals, print statements, some module renaming (esp. urllib), and fixing relative imports. 

Because this change will (likely) touch every .py file in the project, it'll require some coordination to merge.

Thoughts? Objections?

**Comment by jpstroop** [comment]
FWIW I'm +💯 for this, probably supporting 2.7 and >3.5 for now. I think
the hardest part might be the jp2 info extraction, but I've already done
it! I started a major refactor last summer in a separate repo that kind of
fizzled (though it was basically done):

https://github.com/jpstroop/loris-redux/blob/master/loris/info/jp2_extractor.py

It's also much nicer code with better tests, if I say so myself.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by rogerhoward** [comment]
Excellent - was planning to target 2.7/3.5

I think it'd be best to keep the refactor and this compatibility push separate - I'm a little afraid of the refactor without better test coverage (re: #325 and @alexwlchan comments). The 2/3 compatibility is immediately useful, low risk, and a relatively easy job (unsexy as it may be).

This is also a good chance for me to get more familiar with the code/architecture, while I help out on the outskirts.

**Comment by jpstroop** [comment]
Yeah, I wouldn't use all of that code, just the jp2 parser: https://github.com/jpstroop/loris-redux/blob/master/loris/info/jp2_extractor.py#L103-L210. There wasn't a straight 2 to 3 upgrade there because of the something to do the `struct` module, if I recall.

**Comment by jpstroop** [comment]
And, I say all of this w/ #323 as one gigantic caveat!

**Comment by bcail** [comment]
@rogerhoward that'd be great to support Python 3! I'm also all for better test coverage, and incremental/low-risk changes. I'm ok with just supporting 3.5 & greater. If anyone would really want 3.4 support, please chime in and let us know.

**Comment by rlskoeser** [comment]
+1 for python 3 support.  I think using `six` makes a lot of sense, I've used that on a few projects that were originally developed for python 2.7.

**Comment by alexwlchan** [comment]
I am tentatively 👍 on six, but let’s see if we need it – I’ve already done the import renaming without it, and less dependencies is usually a good thing.

**Comment by alexwlchan** [comment]
I’ve been raising a bunch of patches to improve the test coverage of Loris, which I think will be a useful safety net for this change.

I’m aiming for a minimum of 100% line coverage, after which I don’t think it should be too hard to get Python 3 support – I already have a tox.ini with Python 3 (although lots of tests fail right now!).

**Comment by alexwlchan** [comment]
I think there’s a general consensus that we go for 2.7 and 3 compatibility?

I’ve added Python 3 tests to Travis – just for information, not for pass/fail. When they go green, we can promote them to proper tests!

I’ve done enough on this now, and Python 3 compatibility isn’t high on my wishlist – so I won’t do any more work on this for a while. If somebody else wants to work on this, I’d suggest picking off bits at a time – lots of small PRs are easier to review and merge than one massive “add Python 3” PR.

**Comment by bcail** [comment]
PR #400 - Loris is now compatible with 2.7, 3.4, 3.5, and 3.6.
