### ISSUE TITLE
Loris can fail to set the Access-Control-Allow-Origin if using the cors_regex setting

### ISSUE THREAD

**Issue by alexwlchan** [loris-imageserver/loris#361]
The `set_acao()` method on `LorisResponse` is defined as follows:

```python
def set_acao(self, request, regex=None):
    if regex:
        if regex.search(request.url_root):
            self.headers['Access-Control-Allow-Origin'] = request.url_root
    else:
        self.headers['Access-Control-Allow-Origin'] = "*"
    self.headers['Access-Control-Allow-Methods'] = "GET, OPTIONS"
    self.headers['Access-Control-Allow-Headers'] = "Authorization"
```

If a regex is present but `request.url_root` doesn't match, it never sets the ACAO header. This seems like an oversight – in this case, it seems like `*` would be a more appropriate value?

The only value to the `regex` parameter is `self.cors_regex`, where `cors_regex` is a setting with minimal documentation and, as far as I can tell, no tests.

**Comment by bcail** [comment]
I think that functionality is tested here: https://github.com/loris-imageserver/loris/blob/development/tests/webapp_t.py#L301. I think the idea is that if cors_regex is set, then you don't want just any origin to be allowed - only origins you've allowed with your regex. @jpstroop any thoughts?

**Comment by jpstroop** [comment]
Yes, that was the intent. I believe the discussion was here: https://github.com/loris-imageserver/loris/issues/181

**Comment by bcail** [comment]
@alexwlchan are you OK with closing this issue? Maybe we should add some documentation and/or code comments to make things clearer.

**Comment by alexwlchan** [comment]
So if the origin doesn’t match your regex, we don’t allow cross-origin sharing? In that case, is it okay to omit the header, or should we be sending the header with some sort of null/empty value?

**Comment by bcail** [comment]
[Looks like](https://stackoverflow.com/a/46087244) it's OK to leave out the header completely.

**Comment by bcail** [comment]
@alexwlchan OK to close?

**Comment by alexwlchan** [comment]
Yep, good to close.
