### ISSUE TITLE
How is the extraInfo parameter in ImageInfo meant to work?

### ISSUE THREAD

**Issue by alexwlchan** [loris-imageserver/loris#369]
There’s a snippet of code in the constructor for ImageInfo as follows, which appears to pass the value of an `extraInfo` key through directly:

```python
for (k, v) in extra.get('extraInfo', {}).items():
    setattr(self, k, v)
```

I’m trying to add a test for this code, because it’s not currently exercised by the tests. There’s a comment in #298 which describes the intended use case:

> Each key, value in `extraInfo` would be copied into the info.json verbatim.

I understood this to mean arbitrary key-value pairs, but trying that gets an AttributeError. For example:

```pycon
>>> from loris.img_info import ImageInfo
>>> ImageInfo(extra={'extraInfo': {'foo': 'bar', 'bar': 'baz'}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "loris/img_info.py", line 82, in __init__
    setattr(self, k, v)
AttributeError: 'ImageInfo' object has no attribute 'foo'
```

Looking at the [IIIF Image spec](http://iiif.io/api/image/2.1/#table-of-contents), it doesn’t look like there’s support for arbitrary parameters in `info.json`, so is this just intended to be a passthrough for the `attribution`, `license`, `logo` and `service` fields?

/cc @azaroth42 as the original author of this code

**Comment by azaroth42** [comment]
Yes, it's a passthrough. ImageInfo only accepts a certain set of slots, so trying to set `foo` will cause a failure, whereas setting `service` to an arbitrary value should work.
