### ISSUE TITLE
Missing character into constants._IDENT

### ISSUE THREAD

**Issue by zannkukai** [loris-imageserver/loris#378]
Hello,

I'm currently using Loris to serve image from a FedoraCommons repository (3.5)
Checking the documentation, I found the perfect way to use Loris using TemplateHTTPResolver.
For a same object, I can have multiple images. My URL's looks like this
 
> http://myserver.com/fedora/objects/test:12345/datastreams/IMG_0001/content
       http://myserver.com/fedora/objects/test:12345/datastreams/IMG_0002/content
  ...

So I would used this configuration : 

> [resolver]
&nbsp;&nbsp;&nbsp;impl = 'loris.resolver.TemplateHTTPResolver'
&nbsp;&nbsp;&nbsp;cache_root='/usr/local/share/images/loris'
&nbsp;&nbsp;&nbsp;delimiter = "|"
&nbsp;&nbsp;&nbsp;templates = 'fedora_obj_ds'
&nbsp;&nbsp;&nbsp;uri_resolvable=False
&nbsp;&nbsp;&nbsp;head_resolvable=False
[[fedora_obj_ds]]
&nbsp;&nbsp;&nbsp;url = 'http://localhost:8080/fedora/objects/%s/datastreams/%s/content'

So my Loris URL's should be

> /loris/fedora_obj_ds:test:12345|IMG_0001/full/full/0/default.jpg
/loris/fedora_obj_ds:test:12345|IMG_0002/full/full/0/default.jpg

Using the default delimiter "|" mentionned into the loris.conf file, it doesn't work. The LorisRequest.request_type has "redirect_info" value.
Chekcing deeper the code the problem comes from LorisRequest._dissect_uri method. At line 275

`image_match = constants.IMAGE_RE.match(self._path)`

The regexp doesn't match because "|" character isn't allowed into constants.py._IDENT.
Fix this problme is very easy (when we found the problem), adding this character into the constant ::

`(-)  _IDENT = r'(?P<ident>[\w:\-\.\%\/]+)'`
`(+) _IDENT = r'(?P<ident>[\w:|\-\.\%\/]+)'`

Sure, we can use another delimiter, but as "|" is mentionned by default, I think it's easier to update the constant for next release.

Hope it helps

**Comment by alexwlchan** [comment]
Thanks for the report!

> I think it's easier to update the constant for next release.

Ideally, I think that regex should really be adapting to your `delimiter` config, and adding the delimiter character to the list of accepted ID characters – but then we might need to check we weren’t allowing any particularly problematic characters there. Maybe updating the IDENT is easiest for now.

**Comment by bcail** [comment]
Fixed in #389.
