### ISSUE TITLE
Can not create a cache copy of the image in Centos 7

### ISSUE THREAD

**Issue by ashmashrest** [loris-imageserver/loris#379]
I am getting below error when the cache is turned on. We are using Centos 7, same configuration in Ubuntu 16.04 seems to be working fine. I tired turning off SELinux but there error still exists. I am using a AWS s3fs mount as the image source root, however changing the image source root  to "/usr/local/share/image" has the same issue. 

Below is the snippet of the error log -
File "/usr/lib/python2.7/site-packages/Loris-2.2.0-py2.7.egg/loris/img.py", line 278, in upsert
rename(temp_fp, target_fp)
OSError: [Errno 18] Invalid cross-device link

**Comment by alexwlchan** [comment]
Yeah, so Loris downloads images from the source to a temporary directory, then uses `os.rename` to copy the file into a permanent cache. There is a note in the docs for `os.rename`:

> The operation may fail on some Unix flavors if _src_ and _dst_ are on different filesystems. 

So I’d guess that either:

* On CentOS, your temporary directory is on a different filesystem to your permanent cache, and on Ubuntu it isn't; or
* CentOS complains about renaming across filesystems in a way that Ubuntu doesn't

It feels to me like the most robust fix would be to switch to using `shutil.move`, which I think is filesystem-aware. @bcail does that sound sensible to you?

Related: #303.

**Comment by alexwlchan** [comment]
(Sorry, hit the wrong button there!)

**Comment by ashmashrest** [comment]
Thanks @alexwlchan . I came across the workaround yesterday but guess I implemented it incorrectly. Switching rename to shutil.move seemed to have fixed the issue. I am using the same setup in Ubuntu - s3fs mount as the image source root, /tmp/loris2 as the temp directory and /var/cache/loris as the cache directory but guess Centos does not play nice with different file systems.

**Comment by alexwlchan** [comment]
Glad to hear you resolved it @ashmashrest!

I’ll keep this issue open – we should probably modify vanilla Loris to use `shutil.move()`, so we’ll use this issue for tracking that.

**Comment by ashmashrest** [comment]
That sounds good.

**Comment by bcail** [comment]
#300 is relevant here. I think the issue is whether we're going to provide a guarantee that the move is atomic or not. If it's not atomic, users might see a partially written file in the cache. It looks like shutil.move uses os.rename if it's the same filesystem (so it's atomic), but if it's a different filesystem, it uses copy2 (which wouldn't be atomic, I don't think).

The solution that we do is to point tmp_dp to the same filesystem as all the cache directories.

@giorgiosironi might have some thoughts.

**Comment by giorgiosironi** [comment]
Will check the proposed `shutil.move`, interesting to have a solution that is aware of the different filesystem. Notice that if the change is not atomic it can break some images outputting them as incomplete on a 200 response; but on low traffic that should be unlikely to happen.

**Comment by alexwlchan** [comment]
How hard is it to detect if the two directories are on different filesystems? Could we do something like:

```python
def safe_move(src, dst):
    if on_different_filesystems(src, dst):
        shutil.move(src, dst + '.tmp')
        os.rename(dst + '.tmp', dst)
    else:
        os.rename(src, dst)
```

**Comment by bcail** [comment]
Looks like shutil.move does a try...except: https://github.com/python/cpython/blob/2.7/Lib/shutil.py#L307

Maybe we could combine the ideas: try the rename, if it fails with that error, do the copy to a tmp file and rename the tmp file.

How does that sound?

**Comment by alexwlchan** [comment]
> Maybe we could combine the ideas: try the rename, if it fails with that error, do the copy to a tmp file and rename the tmp file.

Yep, that sounds good to me.
