### ISSUE TITLE
Loris seemingly unable to process TIF files

### ISSUE THREAD

**Issue by minusdavid** [loris-imageserver/loris#405]
I'm pointing Loris at a Fedora 4.7.2 instance and it's working great using Kakadu for JPEG2000, but I'm seeing the following for TIFFs:

Server Side Error: -2 

This is likely a permissions problem, though it's
possible that there was a problem with the source file
(/usr/local/share/images/loris/7b/977/74f/905/03d/4a6/a43/099/a4d/8f5/193/loris_cache.tif). (500)

I'm able to download and render the TIFF from Fedora directly and I doubt it's a permission problem since the permissions look fine and JPEG2000 is working in the image cache. 

I'm guessing it's an issue with Pillow then...

**Comment by minusdavid** [comment]
I know https://github.com/loris-imageserver/loris/blob/development/doc/dependencies.md says that "pip install Pillow" should say the following:

[...]
--- JPEG support available
[...]
--- ZLIB (PNG/ZIP) support available
--- LIBTIFF support available
--- FREETYPE2 support available
--- LITTLECMS2 support available
--- WEBP support available
--- WEBPMUX support available
[...]

However mine did not... it didn't have any output.

**Comment by minusdavid** [comment]
But there are other directions which aren't quite right as well I think (I made some notes to go back to raise issues...)

In the Pillow directories, I see the following:

/usr/local/lib/python2.7/dist-packages/PIL/TiffImagePlugin.py
  /usr/local/lib/python2.7/dist-packages/PIL/TiffImagePlugin.pyc
  /usr/local/lib/python2.7/dist-packages/PIL/TiffTags.py
  /usr/local/lib/python2.7/dist-packages/PIL/TiffTags.pyc

**Comment by minusdavid** [comment]
Uninstalled and installed again... added some verbose flags and still none of that desired output.

**Comment by minusdavid** [comment]
Upgraded pip from 8.1.2 to 9.0.1 and still nothing..

**Comment by minusdavid** [comment]
Note that this is running on Ubuntu 16.04 LTS...

**Comment by minusdavid** [comment]
If I use Pillow from the command line, it can tell that it's a TIFF file... 

Hmm maybe a missing folder? I noticed that there are a large number of directories that setup.py doesn't auto-create...

**Comment by minusdavid** [comment]
Manually made /var/cache/loris but nope...

**Comment by minusdavid** [comment]
Hmm that was certainly related though... as I was getting some errors for that in the Apache logs and now I'm getting my info.json for that TIFF file showing up in /var/cache/loris....

**Comment by minusdavid** [comment]
Errr but there's also a /var/cache/loris2 which seems to have been autocreated...

**Comment by minusdavid** [comment]
Ah wait it was unrelated... just some configuration confusion on my part in regards to /var/cache/loris vs loris2...

Still can't get these TIFs to load via Loris though..

**Comment by minusdavid** [comment]
Just saw this in the Apache logs...

TIFFReadScanline: scanline oriented access is not supported for downsampled JPEG compressed images, consider enabling TIFF_JPEGCOLORMODE as JPEGCOLORMODE_RGB..

**Comment by minusdavid** [comment]
That comes up when I restart Apache...

**Comment by minusdavid** [comment]
Hmm perhaps related to https://github.com/python-pillow/Pillow/issues/2926 ?

**Comment by minusdavid** [comment]
Ha! That was it!

I tried using version 4.3.0 of Pillow since they mentioned it worked in that bug report and sure enough... after running "pip install Pillow==4.3.0", Loris will now render the TIF. 

Cleared the cache in /var/cache/loris2, reinstalled Pillow 5.0.0, and nada. Error message once again.

Yikes...

**Comment by alexwlchan** [comment]
Okay, so it sounds like we should be stricter about the version of Pillow we support – and since Loris is an application, not a library, we should really provide exact, known, working pins.

Thanks for the report!
