### ISSUE TITLE
setup.py can't be run with pip 10

### ISSUE THREAD

**Issue by alexwlchan** [loris-imageserver/loris#421]
We have these lines in our setup.py:

```python
from pip.download import PipSession
from pip.req import parse_requirements
```

but pip 10 deliberately removed all these internal APIs. We should remove them, and find an alternative way to specify requirements.

**Comment by minusdavid** [comment]
I ran into this little chestnut yesterday...

I changed the lines to the following as a workaround:
```
from pip._internal.download import PipSession
from pip._internal.req import parse_requirements
```
But obviously that's not a real solution.
