### ISSUE TITLE
Basic LRU features for Loris Cache

### ISSUE THREAD

**Issue by captmiddy** [loris-imageserver/loris#422]
As we are moving toward implementation in production, one thing we noticed is that using the standard cache management features, we would be deleting things that are used and leaving behind things that aren't based on timing.  The current method by which items are retrieved does not touch cached objects to make them appear current.  What I am wondering is if it would make sense to have the cache retrieval functions actually touch the item that is cached thus making it get a new modified date.  Then using find with modify date, we can delete old items or those that haven't been used recently but keep items that are used all the time.  Our goal is to cache elements that are used for classes and keep them cached because they are used frequently but allow single use images to disappear after a few days from the cache.

Any suggestions on how this might be achieved quickly without breaking upgrade? Might this be a feature more people are interested in?  I noticed in the diskless talk that LRU cache was suggested as well.

**Comment by alexwlchan** [comment]
What are you using to clear the cache?

We provide a couple of scripts in the `bin` directory, which both use access time, not modified time, to determine which items to purge first – so I don’t think they’d be affected by this issue?

You configure them with a max disk size you want to use, and then cache items are deleted, last accessed first, until you get under that max size.

https://github.com/loris-imageserver/loris/blob/9861c6f3882cc379ab0880a19604cecc933e76f8/bin/loris-cache_clean.sh#L57-L60

https://github.com/loris-imageserver/loris/blob/9861c6f3882cc379ab0880a19604cecc933e76f8/bin/loris-http_cache_clean.sh#L47-L56

**Comment by captmiddy** [comment]
Actually I went back to your original code base and put in our adjustments and it works now.  The original mount I had wasn't supporting atime from find.  I have since moved to Ubuntu for the platform and it is fine now.  I think this can be marked down as user error and you can close it out. Thanks.

**Comment by alexwlchan** [comment]
Okay, glad you got it sorted!
