### ISSUE TITLE
Inconsistent handling of special characters

### ISSUE THREAD

**Issue by onbcst** [loris-imageserver/loris#432]
Special characters in the path to an imge are not handled the same way if a) the `info.json` for that file is requested or b) an actual image using iiif syntax (e.g. `full/full/0/default.jpg`) is requested. For the first case _loris_ returns the valid `info.json` for that image resource. For the latter case _loris_ does not correctly resolve the folder structure and therefore returns `Not Found: could not resolve identifier: %2Babc%2Ftest.png%2Ffull%2Ffull%2F0%2Fdefault.jpg  (404)`.

Steps to recreate this behavior:
```sh
git clone https://github.com/loris-imageserver/loris
cd loris/
pip install -r requirements.txt
# create folder with special character and copy dummy image to it`
mkdir -p tests/img/+abc && cp tests/img/test.png tests/img/+abc
python loris/webapp.py
```
Then call either `http://127.0.0.1:5004/+abc/test.png/info.json` or `http://127.0.0.1:5004/+abc/test.png/full/full/0/default.jpg`.

For this particular case using the `+`-symbol a solution would be adding the `+` to the regex in [constants.py](https://github.com/loris-imageserver/loris/blob/0d9e84bc5174cd1403669355971844e7d4cf8ef5/loris/constants.py#L40). This solution though does not resolve problems regarding other special characters and does not tackle the core problem of the inconsistent handling.

**Comment by bcail** [comment]
@onbcst yes, we handle images and info differently in webapp.py. Seems like it would be good to have a consistent matching of identifiers, whether it's for an image or info.json. Feel free to submit a PR if you want.
