### ISSUE TITLE
@id value in info.json point to different ipaddress

### ISSUE THREAD

**Issue by AK-Bharath** [loris-imageserver/loris#436]
Hi There,

My iiifserver ipaddress is `54.252.92.17` and info.json path is `http://54.252.92.17/iiif/417ab3b4-7452-4f7e-a59f-edd068693938/info.json` and its contents are 

```json
{
    "profile": [
        "http://iiif.io/api/image/2/level2.json",
        {
            "supports": [
                "canonicalLinkHeader",
                "profileLinkHeader",
                "mirroring",
                "rotationArbitrary",
                "regionSquare",
                "sizeAboveFull"
            ],
            "qualities": [
                "default",
                "color",
                "gray",
                "bitonal"
            ],
            "formats": [
                "jpg",
                "png",
                "gif",
                "webp"
            ]
        }
    ],
    "protocol": "http://iiif.io/api/image",
    "sizes": [

    ],
    "height": 3199,
    "width": 5254,
    "@context": "http://iiif.io/api/image/2/context.json",
    "@id": "http://54.252.86.234/iiif/417ab3b4-7452-4f7e-a59f-edd068693938"
}
```

here id is pointing to different ip address http://54.252.86.234
but my application runs on http://54.252.92.17 
and info.json path is http://54.252.92.17/iiif/417ab3b4-7452-4f7e-a59f-edd068693938/info.json

secondly I get Tile error on browser console
default.jpg:1 GET http://54.252.86.234/iiif/417ab3b4-7452-4f7e-a59f-edd068693938/full/657,/0/default.jpg 404 (NOT FOUND)
which is referring to 54.252.86.234,   

this ipaddress is one of our demo machine, I am not able to find out how it is picking this ipaddress.

I am using loris-2.1.0-final

Please help me in fixing this issue.

with many thanks,

Bharath AK

**Comment by alexwlchan** [comment]
Can you share your `loris2.conf` file? I wonder if you’ve set the `proxy_path` setting to that of your demo machine? That would cause the behaviour you’re seeing.

Specifically, config a bit like this:

```ini
[loris.Loris]
proxy_path = 'http://54.252.86.234/'
```

because that setting is used to populate the `@id` value in the info.json file.

**Comment by AK-Bharath** [comment]
Hi There,
      Thanks for your response.  
It fails for only a few images and a few images are working properly.
nginx.conf details
////////########/////////
upstream iiifserver {  server unix://tmp/iiifserver.sock;}
server {  listen      80 default_server;  charset     utf-8;  client_max_body_size 5M;
  location / {    if ($arg_download) {      add_header Content-Disposition 'attachment; filename="$arg_download"';    }    uwsgi_pass iiifserver;    include /home/loris/uwsgi_params;  }}
////////########/////////
loris2.conf details
////////########/////////
[loris.Loris]tmp_dp = '/tmp/loris2/tmp' # r--www_dp = '/var/www/loris2' # r-xrun_as_user = 'loris'run_as_group = 'loris'enable_caching = Trueredirect_canonical_image_request = Falseredirect_id_slash_to_info = True
# max_size_above_full restricts interpolation of images on the server.# Default value 200 means that a user cannot request image sizes greater than# 200% of original image size (width or height).# Set this value to 100 to disallow interpolation. Set to 0 to remove# size restriction.max_size_above_full = 200
#proxy_path=''# cors_regex = ''# NOTE: If supplied, cors_regex is passed to re.search():#    https://docs.python.org/2/library/re.html#re.search# Any url_root:#    http://werkzeug.pocoo.org/docs/latest/wrappers/#werkzeug.wrappers.BaseRequest.url_root# (i.e., https?://domain.edu(:port)?/) that matches will be# set to the value of Access-Control-Allow-Origin.
[logging]log_to = 'file'    # 'console'|'file'log_level = 'INFO' # 'DEBUG'|'INFO'|'WARNING'|'ERROR'|'CRITICAL'log_dir = '/var/log/loris2' # rw-max_size = 5242880 # 5 MBmax_backups = 5format = '%(asctime)s (%(name)s) [%(levelname)s]: %(message)s'
[resolver]impl = 'loris.resolver.SimpleFSResolver'src_img_root = '/usr/local/share/images' # r--
[img.ImageCache]cache_dp = '/var/cache/loris' # rwx
[img_info.InfoCache]cache_dp = '/var/cache/loris' # rwx
[transforms]dither_bitonal_images = Falsetarget_formats = ['jpg','png','gif','webp']
    [[jpg]]    impl = 'JPG_Transformer'
    [[tif]]    impl = 'TIF_Transformer'
    [[png]]    impl = 'PNG_Transformer'
    [[jp2]]    impl = 'KakaduJP2Transformer'    tmp_dp = '/tmp/loris/tmp/jp2' # rwx    kdu_expand = '/usr/local/bin/kdu_expand' # r-x    kdu_libs = '/usr/local/lib' # r--    num_threads = '4' # string!    mkfifo = '/usr/bin/mkfifo' # r-x    map_profile_to_srgb = False    srgb_profile_fp = '/usr/share/color/icc/colord/sRGB.icc' # r--
////////########/////////

secondly I get this Tile error on the console logs for failing images which is pointing http://54.252.86.234

default.jpg:1 GET http://54.252.86.234/iiif/417ab3b4-7452-4f7e-a59f-edd068693938/full/657,/0/default.jpg 404 (NOT FOUND)
Tile $.Tile failed to load: http://54.252.86.234/iiif/417ab3b4-7452-4f7e-a59f-edd068693938/full/657,/0/default.jpg - error: Image load aborted

please help me in resolving this issue.
with many thanks,
Bharath AK

   On Thursday, 8 November, 2018, 5:53:22 PM GMT+9:30, Alex Chan <notifications@github.com> wrote: 
 
 
Can you share your loris2.conf file? I wonder if you’ve set the proxy_path setting to that of your demo machine? That would cause the behaviour you’re seeing.

Specifically, config a bit like this:
[loris.Loris]
proxy_path = 'http://54.252.86.234/'
because that setting is used to populate the @id value in the info.json file.

**Comment by AK-Bharath** [comment]
Hi Alex,
       Thanks for your time and help.  I had fixed this. the reason for this issue is, it is not picking the environment variable.  I had set the environment variable and restarted it  Then it started working.
Thanks for your time and help.
With Many thanks, 
Bharath AK
   ----- Forwarded message ----- From: A K Bharath <ak_bharath@yahoo.in>To: loris-imageserver/loris <loris@noreply.github.com>; loris-imageserver/loris <reply@reply.github.com>Cc: Author <author@noreply.github.com>Sent: Friday, 9 November, 2018, 8:26:20 AM GMT+9:30Subject: Re: [loris-imageserver/loris] @id value in info.json point to different ipaddress (#436)
  Hi There,
      Thanks for your response.  
It fails for only a few images and a few images are working properly.
nginx.conf details
////////########/////////
upstream iiifserver {  server unix://tmp/iiifserver.sock;}
server {  listen      80 default_server;  charset     utf-8;  client_max_body_size 5M;
  location / {    if ($arg_download) {      add_header Content-Disposition 'attachment; filename="$arg_download"';    }    uwsgi_pass iiifserver;    include /home/loris/uwsgi_params;  }}
////////########/////////
loris2.conf details
////////########/////////
[loris.Loris]tmp_dp = '/tmp/loris2/tmp' # r--www_dp = '/var/www/loris2' # r-xrun_as_user = 'loris'run_as_group = 'loris'enable_caching = Trueredirect_canonical_image_request = Falseredirect_id_slash_to_info = True
# max_size_above_full restricts interpolation of images on the server.# Default value 200 means that a user cannot request image sizes greater than# 200% of original image size (width or height).# Set this value to 100 to disallow interpolation. Set to 0 to remove# size restriction.max_size_above_full = 200
#proxy_path=''# cors_regex = ''# NOTE: If supplied, cors_regex is passed to re.search():#    https://docs.python.org/2/library/re.html#re.search# Any url_root:#    http://werkzeug.pocoo.org/docs/latest/wrappers/#werkzeug.wrappers.BaseRequest.url_root# (i.e., https?://domain.edu(:port)?/) that matches will be# set to the value of Access-Control-Allow-Origin.
[logging]log_to = 'file'    # 'console'|'file'log_level = 'INFO' # 'DEBUG'|'INFO'|'WARNING'|'ERROR'|'CRITICAL'log_dir = '/var/log/loris2' # rw-max_size = 5242880 # 5 MBmax_backups = 5format = '%(asctime)s (%(name)s) [%(levelname)s]: %(message)s'
[resolver]impl = 'loris.resolver.SimpleFSResolver'src_img_root = '/usr/local/share/images' # r--
[img.ImageCache]cache_dp = '/var/cache/loris' # rwx
[img_info.InfoCache]cache_dp = '/var/cache/loris' # rwx
[transforms]dither_bitonal_images = Falsetarget_formats = ['jpg','png','gif','webp']
    [[jpg]]    impl = 'JPG_Transformer'
    [[tif]]    impl = 'TIF_Transformer'
    [[png]]    impl = 'PNG_Transformer'
    [[jp2]]    impl = 'KakaduJP2Transformer'    tmp_dp = '/tmp/loris/tmp/jp2' # rwx    kdu_expand = '/usr/local/bin/kdu_expand' # r-x    kdu_libs = '/usr/local/lib' # r--    num_threads = '4' # string!    mkfifo = '/usr/bin/mkfifo' # r-x    map_profile_to_srgb = False    srgb_profile_fp = '/usr/share/color/icc/colord/sRGB.icc' # r--
////////########/////////

secondly I get this Tile error on the console logs for failing images which is pointing http://54.252.86.234

default.jpg:1 GET http://54.252.86.234/iiif/417ab3b4-7452-4f7e-a59f-edd068693938/full/657,/0/default.jpg 404 (NOT FOUND)
Tile $.Tile failed to load: http://54.252.86.234/iiif/417ab3b4-7452-4f7e-a59f-edd068693938/full/657,/0/default.jpg - error: Image load aborted

please help me in resolving this issue.
with many thanks,
Bharath AK

   On Thursday, 8 November, 2018, 5:53:22 PM GMT+9:30, Alex Chan <notifications@github.com> wrote: 
 
 
Can you share your loris2.conf file? I wonder if you’ve set the proxy_path setting to that of your demo machine? That would cause the behaviour you’re seeing.

Specifically, config a bit like this:
[loris.Loris]
proxy_path = 'http://54.252.86.234/'
because that setting is used to populate the @id value in the info.json file.

**Comment by alexwlchan** [comment]
Glad you got it working! 🎉

I’ll close this issue now – create a new issue if you have any other problems.
