### ISSUE TITLE
Drop python2 support in development?

### ISSUE THREAD

**Issue by bcail** [loris-imageserver/loris#450]
Python 2 is going EOL on 1/1/2020. Are there any concerns with dropping Python 2 support in the development branch now? Of course all the releases up till now still work with Python 2, and will continue to be available...

**Comment by alexwlchan** [comment]
More than happy to!

**Comment by bcail** [comment]
Great, I'll plan to submit a PR dropping py2 CI testing.

**Comment by alexwlchan** [comment]
While we’re at it, let’s target a fairly modern Python 3 – we still have Python 3.4 in our Travis matrix, even though it’s EOL as well.
