### ISSUE TITLE
Deploying Loris with nginx

### ISSUE THREAD

**Issue by lguariento** [loris-imageserver/loris#451]
Hello, are there ay instructions for nginx? Apache and Docker are there, it'd be great if there was some information about nginx too. Thanks!

**Comment by bcail** [comment]
@lguariento a PR to add those instructions would be welcome. (Note: loris is just a regular WSGI app, so instructions for deploying a WSGI app with nginx should help with loris as well.)

**Comment by lguariento** [comment]
Done: #461

**Comment by lguariento** [comment]
I've also added the link to the readme.md file (#462)
