### ISSUE TITLE
Loris https and caching

### ISSUE THREAD

**Issue by ericvanderlinden** [loris-imageserver/loris#454]
Could there be any reason for Loris to stop caching when we move to https?

If not, what could, in general, be the reason for Loris to stop caching.

**Comment by alexwlchan** [comment]
I can’t think of a reason.

All the caching that Loris does happens before the HTTP/HTTPS layer, specifically:

* It caches the original, full-resolution images from the source
* It caches the processed (cropped, rotated, resized, etc.) images that are sent to the client
* It caches the image info (resolution, colour profile, etc.)

I don’t think any of those would be affected by Loris running in front of HTTPS. We run Loris behind HTTPS for iiif.wellcomecollection.org, and we haven’t seen any caching issues.

If you’re running a caching layer separate to Loris (e.g. a CDN like CloudFront or CloudFlare), that might be affected, but that’s independent of Loris.

Are you asking hypothetically, or have you moved Loris to run behind HTTPS and seen caching problems?

**Comment by ericvanderlinden** [comment]
No unfortunately not hypothetically. Moving to HTTPS and Loris stop caching happened at the same time. It also stopped logging except for a couple of hours on Saturday and a couple of minutes on Monday.
No error messages in Apache error log, no entries in loris access log. And suddenly two directories created in cache named  88 and b7.
I tested writing files and making dirs as user loris in tmp and cache and that was no problem.

I was just wondering if you had some experience with HTTPS. I had not realized that Loris caching is independent of HTTP/HTTPS.

Loris seems to be completely ignored by Apache, so after reading your comment I think it may be something in configuration. I will move back to HTTP and original set up. See what happens.

I'm working on a virtual server. 
https://www.leaseweb.com/nl/cloud/public/virtual-server
But it should not make any difference.

**Comment by ericvanderlinden** [comment]
Well thanks for the comments. Back on HTTP. There must something wrong in HTTPS configuration. Maybe the mixed environment. At least the logging is back. 

There is a 303  redirect I do not understand. I saw that before. Any ideas why that happens. It seems to trick Loris in not finding the resource. The resource is definitely there.

2019-05-28 09:21:50,296 (urllib3.connectionpool) [DEBUG]: http://<domainname>:80 "GET /loris/albert/01/PHID000000002.jpg HTTP/1.1" 303 0

2019-05-28 09:21:50,299 (urllib3.connectionpool) [DEBUG]: http://<domainname>:80 "GET /loris/albert%2F01%2FPHID000000002.jpg/info.json HTTP/1.1" 404 331

2019-05-28 09:21:50,300 (loris.resolver) [WARNING]: Source image not found at http://<domainname>/loris/albert/01/PHID000000002.jpg for identifier: albert/01/PHID000000002.jpg. Status code returned: 404.

**Comment by ericvanderlinden** [comment]
I think after looking around in the resolver and webapp I think this 303 also happens after the caching.
So something goes wrong with getting the ID of the file and creating the directories in the cache.
