### ISSUE TITLE
Loris sends (undesirably) sends rules.json for every image resolution

### ISSUE THREAD

**Issue by minusdavid** [loris-imageserver/loris#492]
It would be nice to disable the sending of the rules.json request, as it's creating unnecessary HTTP traffic

**Comment by bcail** [comment]
@minusdavid thanks, I agree. I'll work on that, but first I have a general question for anyone.

@azaroth42, @alexwlchan, anyone:
The ImageInfo class takes in an "extra" parameter, which contains authentication information (coming from the rules.json file for the image), but the extra parameter also contains "extraInfo", which can set non-auth information like the logo, attribution, and license for the image info (see https://github.com/loris-imageserver/loris/blob/development/loris/img_info.py#L83, https://github.com/loris-imageserver/loris/blob/development/loris/img_info.py#L95, https://github.com/loris-imageserver/loris/blob/development/tests/img_info_t.py#L265). Is that functionality being used? Ie. are rules.json files being used for non-auth information (like logo, license, ...) for images, or can we limit the rules.json file handling to just auth information?

**Comment by alexwlchan** [comment]
> are rules.json files being used for non-auth information (like logo, license, ...) for images

We’re not using rules.json at all at Wellcome, so no.

**Comment by azaroth42** [comment]
We used to use it for that, but have switched away from Loris.

**Comment by bcail** [comment]
should be fixed in #495.
