### ISSUE TITLE
Loris 3.0 release

### ISSUE THREAD

**Issue by bcail** [loris-imageserver/loris#498]
What are the next steps for a 3.0 release? I'd like to get the Pillow version updated, which I don't think will be a big deal (I'd be OK with going ahead and merging #485). Are there any other changes we should get in before releasing 3.0?

This is a major release: we dropped python 2 support, and have made changes to the cache layout so caches will need to be rebuilt.

@alexwlchan, others - any thoughts?

**Comment by minusdavid** [comment]
I'm not entirely sure but would be very excited to get #497 in there. 

I see the "development" branch is the default. Is there no master or stable branch? What's the current master/stable point in the code? https://github.com/loris-imageserver/loris/commit/66977fe3135242439038aa2a49292c2acfca3bb3 would be another one I'd like to see added to cut down significantly on the amount of unnecessary HTTP requests we're doing atm.

**Comment by minusdavid** [comment]
(As a side note, are @bcail and @alexwlchan the only active developers/maintainers these days?)

**Comment by bcail** [comment]
@minusdavid for #497 503/504 errors - those might be fixed already in the development branch... are you able to test the latest dev branch? Or, are you able to capture a stack trace when it happens?

Yes, the "development" branch is the current master branch, and that's what we would tag with a new release (so 66977fe would be included in the new release). And yes, we don't have many developers working on loris - you'd be welcome to join. :)

**Comment by minusdavid** [comment]
Ooops I meant [https://github.com/loris-imageserver/loris/commit/8855cc958c8fbe7ac523e902a0424563b1da430e](url), but if the development branch is the master branch then nevermind me. Misunderstanding on my part.

The next step for us would be to run up a newer stable version (like 3.0.0) and see how it goes from there. Then if there are issues, more of a deep dive will be done (provided there is funding). 

Cheers thanks for that :). We're starting to ramp up our use of Loris, with some interesting collections in Australia, so I might be doing more work on it. I always like upstreaming work wherever possible!

**Comment by minusdavid** [comment]
How are we going on this one?

**Comment by alexwlchan** [comment]
(Sorry, have been somewhat busy/not in the office – haven’t been chiming in but broadly in agreement with what’s already been said, and I’ll have more time to work on Loris stuff again next week.)

**Comment by minusdavid** [comment]
By the way @alexwlchan I like what you wrote at https://stacks.wellcomecollection.org/using-loris-for-iiif-at-wellcome-6ed1fefaf801. I'm going to reconsider how we're running Loris at the moment in light of that write up. 

We're actually stalled on our Loris work until Loris 3.0 is released, but after it comes out, we'll do an upgrade, and hopefully be doing more with it.

**Comment by bcail** [comment]
I deployed the latest code to our production system yesterday, and it seems fine so far.

@alexwlchan is it OK if we release 3.0 this week, or is there something else you want to get in?

**Comment by alexwlchan** [comment]
> By the way @alexwlchan I like what you wrote at https://stacks.wellcomecollection.org/using-loris-for-iiif-at-wellcome-6ed1fefaf801. I'm going to reconsider how we're running Loris at the moment in light of that write up.

Thanks @minusdavid! It hasn't changed much since then, so feel free to ask questions. All our infra is on GitHub, so I can send you links if it's useful.

> is it OK if we release 3.0 this week, or is there something else you want to get in?

I’m happy to release 3.0 this week.

**Comment by minusdavid** [comment]
> Thanks @minusdavid! It hasn't changed much since then, so feel free to ask questions. All our infra is on GitHub, so I can send you links if it's useful.

Thanks! That would be useful :). 

> I’m happy to release 3.0 this week.

This would be great!

**Comment by alexwlchan** [comment]
v3.0.0! https://github.com/loris-imageserver/loris/releases/tag/v3.0.0
