### ISSUE TITLE
mkfifo, permission denied?

### ISSUE THREAD

**Issue by mmcclimon** [loris-imageserver/loris#52]
I'm having some trouble deploying loris on RHEL6 using mod_wsgi (I don't think this is your fault, but I'm hoping you or someone else here might have some guidance, as I'm not really a python person).

I have everything installed correctly, as far as I can tell. When I try to serve an image, however, the call to '/usr/bin/mkfifo' fails with a permission denied error (from line 279 of `transforms.py`). Changing the call to `os.mkfifo()` doesn't help, so it's not like I have the wrong path to `mkfifo`. 

I can't for the life of me figure this out, and I'm hoping someone can help, or might have had the same issue. I've posted a similar question on StackOverflow:

http://stackoverflow.com/questions/21260404/mod-wsgi-cant-run-mkfifo

Thanks!

**Comment by jpstroop** [comment]
This may be obvious, but does the user that's running loris have permission to write to the directory where it's trying to make the FIFO? That's the directory configured here:

https://github.com/pulibrary/loris/blob/development/etc/loris.conf#L17

If you ran the embedded development server and then ran `setup.py`, it MAY have made that directory with you as the owner. Try opening the permissions on that dir once and see what happens.

Thanks for writing,
Jon

**Comment by mmcclimon** [comment]
Right, I checked that. Everything was owned correctly, but there was a strange extended permissions issue (security context in SELinux) that was preventing mod_wsgi from running FIFO commands. That's fixed, but now I'm having other problems (I may comment again later!), so I'll close this now. Thanks!

**Comment by jpstroop** [comment]
OK, thanks. I don't know the details of the issue, but if it's something
you think is worth incorporating into the documentation, please let me know
(or feel free to submit a pull request :-) )
