### ISSUE TITLE
loris behind proxy

### ISSUE THREAD

**Issue by ambs** [loris-imageserver/loris#540]
I know that supposedly `webapp` is not to be used in production. But at the moment, that's what I'm doing :-)
Is there any configuration available on it to set up `proxy_fix`: https://werkzeug.palletsprojects.com/en/2.0.x/middleware/proxy_fix/ ?
I have it behind `traefik`, but it is creating `http` links, instead of `https` links.

Ideas are welcome.

**Comment by bcail** [comment]
https://github.com/loris-imageserver/loris/blob/development/doc/configuration.md#lorisloris
Try setting proxy_path in your config to something starting with https, and see if that works.

**Comment by ambs** [comment]
Yes, it works. Perfect. Thanks
