### ISSUE TITLE
Loris configuration

### ISSUE THREAD

**Issue by busymo** [loris-imageserver/loris#543]
I am trying to configure loris for my server (means loris is running as a proxy in Nginx), HTTP://127.0.0.1:8888 ---> https://philhist-papyri-01.philhist.unibas.ch/loris

[resolver]
impl = 'loris.resolver.SimpleHTTPResolver'
uri_resolvable=True
cache_root='/path/to/images'

Everything is fine so far but in the info.json of the images, I do not get the proper id. The @id that I get is:

"@id": "https, https://philhist-papyri-01.philhist.unibas.ch, philhist-papyri-01.philhist.unibas.ch/1%2Fimages%2F1.RectoIliad19th%28T%29book-IR-enh.jpg"

Does anybody have any idea why this is happening? Thanks in advance!!

**Comment by bcail** [comment]
Note #542. But, does setting proxy_path in your config help at all?

**Comment by busymo** [comment]
Yes, helps a bit. But still, the second part of the URI keeps the same. After setting the proxy path:

"@id": "https://philhist-papyri-01.philhist.unibas.ch/loris/1%2Fimages%2F1.RectoIliad19th%28T%29book-IR-enh.jpg"

I am looking to have it as:

"@id": "https://philhist-papyri-01.philhist.unibas.ch/loris/1/images/1.RectoIliad19th(T)book-IR-enh.jpg"
 

> Note #542. But, does setting proxy_path in your config help at all?

**Comment by bcail** [comment]
looks like it's encoding the path - you might have to update the code to not encode it.

**Comment by busymo** [comment]
Yes, I guess it is just encoding some of the characters like in this case  /, ( and ). I think I can check it out and arrive to a solution with it. Thanks for the help!!
