### ISSUE TITLE
Help troubleshooting output from ./test.py

### ISSUE THREAD

**Issue by qurban** [loris-imageserver/loris#59]
I'm working to set up Loris on an internal testing server running Ubuntu 12.04 LTS 64bit.

I've progressed through the instructions and dependency installations at https://github.com/pulibrary/loris and at http://doc.biblissima-condorcet.fr/loris-setup-guide-ubuntu-debian.

The machine is set up with Python 2.7

```
sudo apt-cache show python-dev
```

returns 

```
...
Version: 2.7.3-0ubuntu2.2
...
```

Here's where we get stuck:

```
sudo ./test.py
```

returns 6 errors:

```
test_cleans_up_when_not_caching
test_image_no_redirect_to_cannonical
test_img_reduce
test_img_sends_304
test_no_ims_header_ok
test_redirects_to_default_format_follow
```

All six error originate in:

```
~/loris/tests/webapp_t.py
```

with practically identical tracebacks. I'll quote the test_img_reduce traceback here for reference:

```
===================================================================
ERROR: test_img_reduce (tests.webapp_t.Test_F_WebappFunctional)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nathanael/loris/tests/webapp_t.py", line 180, in test_img_reduce
    resp = self.client.get(to_get)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 761, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 735, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 658, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 854, in run_wsgi_app
    app_iter = app(environ, start_response)
  File "/home/nathanael/loris/loris/webapp.py", line 315, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/nathanael/loris/loris/webapp.py", line 299, in wsgi_app
    response = self.dispatch_request(request)
  File "/home/nathanael/loris/loris/webapp.py", line 309, in dispatch_request
    return getattr(self, 'get_'+endpoint)(request, **values)
  File "/home/nathanael/loris/loris/webapp.py", line 583, in get_img
    fp = self._make_image(image_request, src_fp, src_format)
  File "/home/nathanael/loris/loris/webapp.py", line 631, in _make_image
    transformer.transform(src_fp, target_fp, image_request)
  File "/home/nathanael/loris/loris/transforms.py", line 324, in transform
    im = p.close() # a PIL.Image
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 421, in close
    raise IOError("cannot parse this image")
IOError: cannot parse this image
```

**Comment by qurban** [comment]
Just saw the comments about running individual test modules. That let me confirm that all the errors we're seeing are confirmed from: 

```
sudo python -m unittest -v tests.webapp_t
```

All the other test modules are successful. Thanks!

**Comment by jpstroop** [comment]
Is the ultimate error always `IOError: cannot parse this image`? In the case above, it seems like image is not getting written to the named pipe here:

https://github.com/pulibrary/loris/blob/development/loris/transforms.py#L314-L324

The only place I see that error in Pillow is here: 

https://github.com/python-imaging/Pillow/blob/master/PIL/ImageFile.py#L420-L421

**Comment by qurban** [comment]
You're right. The final error is always `IOError: cannot parse this image`. We installed Pillow via:

```
sudo pip install Pillow
```

I'm pretty sure I recall seeing support for:

```
ZLIB (PNG/ZIP)
TIFF G3/G4
FREETYPE2
LITTLECMS
```

But, I'd be glad to uninstall Pillow and reinstall it with logging to check. Would that help?

One other thing, the instructions on github list `libtiff5-dev` as a dependency. Unfortunately, Ubuntu 12.04 LTS appears only to provide `libtiff4-dev`. Fortunately, the expanded guide at condorcet.fr list `libtiff4-dev` so we blazed ahead.

**Comment by jpstroop** [comment]
I don't think Pillow is getting any data to parse. Could you check 
permissions on whatever directory you've configured at your tmp directory?

https://github.com/pulibrary/loris/blob/development/etc/loris.conf#L17

Could you also confirm that kdu_expand is working properly (just do 
kdu_expand -i some.jp2 -o some.jpg)?

I'm on Ubuntu 12.04 (64-bit) and have never seen this error!

**Comment by qurban** [comment]
I'm with you. I don't have remote access to the server so I'll check in the morning. I appreciate the help. I'll post an update around 9am Central time.

**Comment by jpstroop** [comment]
OK. I'm out of the office until late afternoon tomorrow, but should be able to check in late in the day. If permissions, etc look OK, let's get the rest of the app out of way and see if we can just make a jpeg from a jp2. Change the constants below as necessary; it should make a JPEG at `/tmp/test.jpg` from the jp2 you provide:

``` python
from PIL import Image
from PIL.ImageFile import Parser
from os import makedirs, path, unlink
import subprocess
import sys

KDU_EXPAND='/usr/local/bin/kdu_expand'
LIB_KDU='/usr/local/lib/libkdu_v72R.so'
TMP='/tmp'
INPUT_JP2='/home/jstroop/workspace/loris/tests/img/01/02/0001.jp2'
OUT_JPG='/tmp/test.jpg'

### cmds, etc.
pipe_fp = '%s/mypipe.bmp' % (TMP,)
kdu_cmd = '%s -i %s -o %s' % (KDU_EXPAND, INPUT_JP2, pipe_fp)
mkfifo_cmd = '/usr/bin/mkfifo %s' % (pipe_fp,)
rmfifo_cmd = '/bin/rm %s' % (pipe_fp,)

# make a named pipe
mkfifo_resp = subprocess.check_call(mkfifo_cmd, shell=True)
if mkfifo_resp == 0:
    print 'mkfifo OK'

# write kdu_expand's output to the named pipe 
kdu_expand_proc = subprocess.Popen(kdu_cmd, shell=True, 
    bufsize=-1, stderr=subprocess.PIPE, stdout=subprocess.PIPE,
    env={ 'LD_LIBRARY_PATH' : KDU_EXPAND })

# open the named pipe and parse the stream
with open(pipe_fp, 'rb') as f:
    p = Parser()
    while True:
        s = f.read(1024)
        if not s:
            break
        p.feed(s)
    im = p.close()

# finish kdu
kdu_exit = kdu_expand_proc.wait()
if kdu_exit != 0:
    map(sys.stderr.write, kdu_expand_proc.stderr)
else:
    # if kdu was successful, save to a jpg
    map(sys.stdout.write, kdu_expand_proc.stdout)
    im.save(OUT_JPG, quality=90)

# remove the named pipe
rmfifo_resp = subprocess.check_call(rmfifo_cmd, shell=True)
if rmfifo_resp == 0:
    print 'rm fifo OK'

```

**Comment by qurban** [comment]
Thanks! Quick update this morning. I'll review the testing code shortly.

---

**Regarding tmp directory in loris.conf**

```
cat ~/loris/etc/loris.conf | grep tmp_dp
```

returns

```
tmp_dp=/tmp/loris/tmp
tmp_dp=/tmp/loris/tmp/jp2
```

Initially, `/tmp/loris/tmp` did not exist, but `/tmp/loris` did. So I manually created `/tmp/loris/tmp`. Then:

```
ls -ld /tmp/loris/tmp
```

returned

```
drwxrwxrwx 2 root root 4096 Apr 11 08:33 /tmp/loris/tmp
```

Unfortunately, `sudo python -m unittest -v tests.webapp_t` still returns the same 6 errors.

---

**Regarding `kdu_expand -v`**
At first:

```
kdu_expand -v
```

returned

```
kdu_expand: error while loading shared libraries: libkdu_v72R.so:
cannot open shared object file: No such file or directory
```

So I issued

```
sudo ln -s /usr/local/lib/libkdu_v72R.so /usr/lib/
```

then

```
kdu_expand -v
```

returned

```
This is Kakadu's "kdu_expand" application.
Complied against the Kakadu core system, version v7.2.2.
Current core system version is 7.2.2.
```

Yeah! Onward.

---

**Regarding `kud_expand -i ./sample.jp2 -o ./sample.jpg`**

I copied `~/loris/tests/img/47102787.jp2` to `~/sample.jp2`. Then ran:

```
kdu_expand -i ./sample.jp2 -o ./sample.jpg
```

kdu_expand returned

```
Kakadu Error:
Image file, "sample.jpg, does not have a recognized suffix. Valid suffices are currently:
"bmp", "pgm", "ppm", "tif", "tiff", "raw", and "rawl". Upper or lower case may be used,
but must be used consistently.
```

so we tried

```
kdu_expand -i ./sample.jp2 -o ./sample.bmp
```

that returned

```
Illegal instruction (core dumped)
```

I was able to independently validate the sample.jp2 file using Aperio's ImageScope software so the file itself seems to be fine.

---

**Next steps...**
I'll keep working on getting kdu_expand to work properly from the command line and post updates here as I make progress. Thanks again for your help!

**Comment by qurban** [comment]
I manually upgraded kud_expand to v7.3.3. Same error.

```
kdu_expand -i sample.jp2 -o sample.jpg
```

returns

```
-snip-
Image file, "./sample.jpg" does not have a recognized suffix. Valid suffices are currently:
"bmp", "pgm", "tif", "tiff", "raw", and "rawl".
-snip-
```

Trying it with either `-o sample.bmp` or `-o sample.tif` returns

```
Illegal instruction (core dumped).
```

If I'm interpreting the error messages correctly, jpg isn't an output type supported by these versions of kdu_expand and trying to use one of the supported output types causes it to crash.

**Comment by qurban** [comment]
A bit more information....
I installed openjpeg-tools.

```
sudo apt-get install openjpeg-tools
```

That installs these applications:

```
image_to_j2k
index_create
j2k_to_image
jp2-thumbnailer
```

Then we could run:

```
j2k_to_image -i sample.jp2 -o sample.bmp
```

which returns

```
[INFO] tile 1 of 1
[INFO] - tiers-1 took 0.081026 s
[INFO] -dwt took 0.025848 s
[INFO] -tile decoded in 0.136207 s
Generated Output sample.bmp
```

`sample.bmp` looks identical to `sample.jp2` so that seemed to work.

---

**Which makes me wonder...**
Which version of kdu_expand are you using?

**Comment by jpstroop** [comment]
I'm using kakadu 7.2--I haven't tried 7.3, but it looks like I should.

OpenJpeg is a different JP2 library altogether, that requires different command lines, is much slower, and doesn't yet support all the features we need (last I checked, anyway).

```
kdu_expand -i sample.jp2 -o sample.jpg
```

Will never work. Kakadu can only produces bitmaps, as you saw:

```
Kakadu Error:
Image file, "sample.jpg, does not have a recognized suffix. Valid suffices are currently:
"bmp", "pgm", "ppm", "tif", "tiff", "raw", and "rawl". Upper or lower case may be used,
but must be used consistently.
```

hence this bit of code in the script above:

``` python
# open the named pipe and parse the stream
with open(pipe_fp, 'rb') as f:
    p = Parser()
    while True:
        s = f.read(1024)
        if not s:
            break
        p.feed(s)
    im = p.close()
```

Which is taking the bitmap from the named pipe, parsing it, and transcoding it to a JPEG.

It seems like getting kdu_expand to work on your machine is the key...but I'm stumped. Is there any more to the error? I had a quick Google for it, and found this: http://stackoverflow.com/q/22242000/714478 but no solution....

There's also this thread on the kakadu forums: https://groups.yahoo.com/neo/groups/kakadu_jpeg2000/conversations/topics/6878 I wonder if telling them a little about your hardware might help??

**Comment by qurban** [comment]
Thanks for the feedback. Now that we have a specific issue identified, I'll see what I can do about sorting it out. I'll stay focused on getting `kdu_expand` to work and post back when I've made progress. Thanks again for helping me dissect this.

**Comment by qurban** [comment]
Looks like both the stackoverflow and yahoo groups questions came from the same group. 

There is a discussion in the yahoo group between the original poster and Prof. Taubman. It appears the poster started by compiling directly on the Ubuntu machine. When that didn't work, they compiled it on a Centos based machine and copied the files over. And then it worked.

In that discussion, Prof. Taubman suggests recompiling with the debugging messages turned on to help diagnose the problem. Perfectly reasonable. At the moment, that's a bit beyond the scope of what I can do. I'll keep tinkering.

**Comment by jpstroop** [comment]
@qurban Do keep me posted, and of course let me know if there's anything I can do to help!
