### ISSUE TITLE
Explore namedtuple

### ISSUE THREAD

**Issue by jpstroop** [loris-imageserver/loris#60]
New to me, but may be useful for ImgInfo and any other object that is mostly just data: https://docs.python.org/2/library/collections.html#collections.namedtuple

**Comment by cwulfman** [comment]
Very nice.

Dr. Clifford Wulfman
Coordinator of Library Digital Initiatives
Princeton University
cwulfman@Princeton.EDUmailto:cwulfman@Princeton.EDU

On Apr 18, 2014, at 8:49 AM, Jon Stroop <notifications@github.com<mailto:notifications@github.com>> wrote:

New to me, but may be useful for ImgInfo and any other object that is mostly just data: https://docs.python.org/2/library/collections.html#collections.namedtuplehttps://docs.python.org/2/library/collections.html?utm_campaign=website&utm_source=sendgrid.com&utm_medium=email#collections.namedtuple

**Comment by jpstroop** [comment]
See [this conversation](http://stackoverflow.com/q/2646157/714478). Reports that a class with `__slots__` (what we have now) is over 2x faster than named tuples.

Was thinking about this for ImageInfo (the data carrier part of the object...the fact that there are multiple constructors would complicate things further), but it doesn't look like we'd get a performance boost for the trouble.
