### ISSUE TITLE
OpenJPEG / Glymur

### ISSUE THREAD

**Issue by jpstroop** [loris-imageserver/loris#61]
It's time to start looking at OpenJPEG. Decoding the whole stream is way too slow, but tile access seems acceptable.

Also Glymur:
https://glymur.readthedocs.org/en/latest/introduction.html

Especially if this can ease deployment.

**Comment by ksclarke** [comment]
Would be interesting to see some benchmarking to see how much slower openjpeg is.

**Comment by jpstroop** [comment]
Yeah. I thinking about setting something up...not sure when I'll get a chance, but I'll let you know.

**Comment by jpstroop** [comment]
Consider: http://pillow.readthedocs.org/en/latest/handbook/image-file-formats.html#jpeg-2000
