### ISSUE TITLE
Skip Werkzeug's Routing

### ISSUE THREAD

**Issue by jpstroop** [loris-imageserver/loris#64]
Routing is confusing right now, and is probably adding a lot of overhead with all of those [Rule objects](https://github.com/pulibrary/loris/blob/development/loris/webapp.py#L269-L280). 

We could add more over and confusion by drinking more of the Werkzeug kool-aid with a bunch of custom [Converter](http://werkzeug.pocoo.org/docs/routing/#custom-converters) objects, or instead (better): 
1. Grab the `PATH_INFO` from the environment in `wsgi_app` ([presently here](https://github.com/pulibrary/loris/blob/development/loris/webapp.py#L297-L300))
2. Change `dispatch_request` ([presently here](https://github.com/pulibrary/loris/blob/development/loris/webapp.py#L302-L309)) to use @azaroth42's [regexes](https://github.com/pulibrary/loris/blob/development/loris/webapp.py#L302-L309) and pull out the routing that's baked into `handle` in his impl [here].(https://github.com/azaroth42/py-iiif-image-api/blob/master/wsgi.py#L249)

**Comment by azaroth42** [comment]
In bottle, you can do:

``` python
self.app.route('/%s<identifier>/<rtype>/<name>.json' % self.prefix,
                [method], getattr(self, "%s_single" % method, self.not_implemented))
```

Which then calls get_single() with named params of identifier, rtype and name.
Thus:

``` python
self.app.route('/%s<identifier>/<region>/<size>/<rotation>/<quality>.<format>' ...)
```

And then apply the regexes only to the individual params

**Comment by jpstroop** [comment]
Looks pretty similar to Werkzeug, if you check out [Loris's routing](https://github.com/pulibrary/loris/blob/development/loris/webapp.py#L270-L277). The problem I'm constantly fighting is that WSGI (it's at that level, not Werkzeug) un-escapes slashes (if not everything else), e.g. if you run:

``` python
from wsgiref.simple_server import make_server

def application(environ, start_response):
    body = 'XX'.join(environ['PATH_INFO'].split('/'))
    start_response('200 OK', [])
    return [body] 

make_server('localhost', 5008, application).serve_forever()
```

And then do:

``` bash
curl "http://localhost:5008/loris/my%2Fid%2Fdont%2Fescape/full/full/0/native.jpg"
```

The response body is:

```
XXlorisXXmyXXidXXdontXXescapeXXfullXXfullXX0XXnative.jpg
```

and all of those `/`-based routing patterns work from left to right, on the un-escaped path so one winds up with a mess if there are slashes in the identifier. Even the Werkzeug [Converters](http://werkzeug.pocoo.org/docs/routing/#custom-converters) work this way, which means it's really tough (or at least ugly) to match an identifier with a regex. What I like about your solution is that I can work from right to left on `environ['PATH_INFO']`, popping off the bits (as you say :smile:) as I need them, testing, branching, etc. The only ugliness may be when I get to the  identifier, I may need to factor out `environ['SCRIPT_NAME']` from the left of the string.

All of this said: does [your id regex](https://github.com/azaroth42/py-iiif-image-api/blob/master/wsgi.py#L166) actually work? Seems like it would have the same problem I proofed above? Are you aware of a solution I'm missing?

**Comment by azaroth42** [comment]
Your apache config is set to not decode slashes?

**Comment by jpstroop** [comment]
I have `AllowEncodedSlashes On`. But even if they get through Apache, WSGI un-escapes, no?

**Comment by jpstroop** [comment]
Similar to this: https://github.com/Pylons/pyramid/issues/1008 (though I'm looking for where PEP 333 actually says it).

**Comment by eliotjordan** [comment]
I adapted @azaroth42's ContentDM translator for use with [ERDAS ImageX](https://github.com/eliotjordan/image-api/blob/imagex/translators/ImageX/imagex-iiif-wsgi.py), an obscure geospatial image protocol. The path prefix is removed and the direction of the routing pattens are reversed ( [right to left](https://github.com/eliotjordan/image-api/blob/imagex/translators/ImageX/imagex-iiif-wsgi.py#L235-L266) ) to allow for slashes in the identifier.

Another critical step is to set `AllowEncodedSlashes NoDecode` in Apache (v => 2.2.18), which passes the encoded slashes untouched.

http://map.princeton.edu/iiif/%2Fimages%2F3000%2F00002368.jp2/full/1000,/0/native.jpg

**Comment by jpstroop** [comment]
Awesome! I knew about the Apache directive, but slashes are still getting
decoded by wsgi, no?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by azaroth42** [comment]
That's great Eliot!  Would it be okay to have it in the IIIF repo, or
otherwise linked from it?
