### ISSUE TITLE
[error] IndexError: pop from empty list

### ISSUE THREAD

**Issue by regisrob** [loris-imageserver/loris#99]
Hi Jon,
This is my first test with Loris 2. I think the install is ok, test.py is ok and info.json requests are ok too.
But when requesting default.jpg I have the following error in apache logs. Do you have an idea? 
I'll try another install elsewhere.

<pre>
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40] mod_wsgi (pid=16228): Exception occurred processing WSGI script '/var/www/iiif/loris2/loris.wsgi'.
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40] Traceback (most recent call last):
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40]   File "/mnt/vdata/opt/loris2/env/lib/python2.7/site-packages/Loris-1.2.2dev-py2.7.egg/loris/webapp.py", line 330, in __call__
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40]     return self.wsgi_app(environ, start_response)
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40]   File "/mnt/vdata/opt/loris2/env/lib/python2.7/site-packages/Loris-1.2.2dev-py2.7.egg/loris/webapp.py", line 290, in wsgi_app
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40]     response = self.route(request)
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40]   File "/mnt/vdata/opt/loris2/env/lib/python2.7/site-packages/Loris-1.2.2dev-py2.7.egg/loris/webapp.py", line 313, in route
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40]     size = slices.pop()
[Wed Jul 23 11:00:30 2014] [error] [client 10.14.1.40] IndexError: pop from empty list
</pre>

**Comment by jpstroop** [comment]
Regis,
The routing has been pretty heavily refactored since 1.1. The tests are passing, but it's always possible that I introduced a new bug :wink:. The error is happening here:

https://github.com/pulibrary/loris/blob/development/loris/webapp.py#L313

Could you send me the full URI for the request you're trying to make (it doesn't need to resolve--I just need to see the string).

Thanks!

**Comment by jpstroop** [comment]
(Just a note to self) Problem may be here:

https://github.com/pulibrary/loris/blob/development/loris/webapp.py#L549

What's the significance of `[3:]`? Have a feeling it's inadvertently hard-coded to the tests. Need to add some debug log statements.

Maybe replace it with something this, which is nicer anyway:

``` python
>>> path = '/my/ident/ifier/reg/siz/rot/qual.fmt'
>>> '/'.join(path.split('/')[-4:])
'reg/siz/rot/qual.fmt'
```

**Comment by regisrob** [comment]
The requested URI is:

<pre>
http://mydomain.fr/loris2/T0000009.jp2/full/full/0/default.jpg
</pre>

**Comment by jpstroop** [comment]
OK, thanks. I'll look into it as soon as I get into the office.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by jpstroop** [comment]
Regis,
I was able to reproduce, and the bug was exactly what I thought. Thanks for catching it! I'm 99% sure this will fix it.
-Js

**Comment by regisrob** [comment]
Thanks a lot! You were perfectly right, now it works fine.
I just struggled a little bit with Kakadu: it took me some time to figure out that setup.py had replaced my kdu_expand in "/usr/local/bin"!

**Comment by jpstroop** [comment]
Hmm...do you think that shouldn't be a default? Could be. Want to file a
ticket?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by regisrob** [comment]
I didn't read the updated README, so it's my fault! So yes, I think it's really useful to have it by default, but there is always a chance that your kdu_expand won't work in a given environment or architecture (at least I suppose... because it's my case with an old Debian 6 on our production server). In my opinion your instructions about Kakadu in dependencies.md are clear and sufficient. 
Just one point: having a 64-bit Linux is not a guarantee that kdu will work (it's my case). Actually it seems that it has to do with glibc and libc6 installed on your system (I understood that Kakadu must have been compiled with the same versions of these packages you have on your system... but not sure...).
